/**
 * SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
 * SPDX-License-Identifier: BSD-3-Clause
 */
#include "ph7int.h"
#ifndef PH7_DISABLE_BUILTIN_FUNC
#ifndef PH7_DISABLE_DISK_IO
/*
 * Sessions (NEWPLAN band D): file-backed session_* functions over the
 * existing $_SESSION superglobal. Embedded-PHP chunk, no C thunks — the
 * needed primitives (file IO, random_bytes, serialize, headers_sent,
 * register_shutdown_function) are all hosted builtins. Session files use
 * php's DEFAULT "php" serialize handler format (`key|<serialized>` runs),
 * decoded by a chunk-level fragment scanner, so files interoperate with a
 * stock php install both ways.
 */

static const char zSessionLib[] =
"class __SessS {"
" public static $status = 1;"
" public static $id = '';"
" public static $name = 'PHPSESSID';"
" public static $path = '';"
" public static $wired = false;"
"}"
"function session_status(){ return __SessS::$status; }"
"function session_id($id = null){"
" $old = __SessS::$id;"
" if( $id === null ){ return $old; }"
" if( __SessS::$status === PHP_SESSION_ACTIVE ){"
"  trigger_error('session_id(): Session ID cannot be changed when a session is"
" active', E_USER_WARNING);"
"  return false;"
" }"
" if( headers_sent() ){"
"  trigger_error('session_id(): Session ID cannot be changed after headers have"
" already been sent', E_USER_WARNING);"
"  return false;"
" }"
" __SessS::$id = (string)$id;"
" return $old;"
"}"
"function session_name($name = null){"
" $old = __SessS::$name;"
" if( $name === null ){ return $old; }"
" if( __SessS::$status === PHP_SESSION_ACTIVE ){"
"  trigger_error('session_name(): Session name cannot be changed when a session"
" is active', E_USER_WARNING);"
"  return false;"
" }"
" if( headers_sent() ){"
"  trigger_error('session_name(): Session name cannot be changed after headers"
" have already been sent', E_USER_WARNING);"
"  return false;"
" }"
" __SessS::$name = (string)$name;"
" return $old;"
"}"
"function session_save_path($path = null){"
" if( __SessS::$path === '' ){"
"  __SessS::$path = rtrim(sys_get_temp_dir(), '/');"
" }"
" $old = __SessS::$path;"
" if( $path === null ){ return $old; }"
" if( __SessS::$status === PHP_SESSION_ACTIVE ){"
"  trigger_error('session_save_path(): Session save path cannot be changed when"
" a session is active', E_USER_WARNING);"
"  return false;"
" }"
" __SessS::$path = rtrim((string)$path, '/');"
" return $old;"
"}"
"function __sess_file(){"
" return session_save_path() . '/sess_' . __SessS::$id;"
"}"
"function __sess_genid(){"
" $chars = '0123456789abcdefghijklmnopqrstuv';"
" $raw = random_bytes(32);"
" $out = '';"
" for( $i = 0; $i < 32; $i++ ){ $out .= $chars[ord($raw[$i]) & 31]; }"
" return $out;"
"}"
"function __sess_scan_fragment($s, $p){"
" /* Return the position just past ONE serialized value starting at $p"
"  * (enough of php's serialize grammar for session payloads). */"
" $c = $s[$p] ?? '';"
" if( $c === 'N' ){ return $p + 2; }"
" if( $c === 'i' || $c === 'd' || $c === 'b' ){"
"  $e = strpos($s, ';', $p);"
"  return $e === false ? strlen($s) : $e + 1;"
" }"
" if( $c === 's' ){"
"  $q = strpos($s, ':', $p + 2);"
"  $len = (int)substr($s, $p + 2, $q - ($p + 2));"
"  return $q + 1 + 1 + $len + 2;"
" }"
" if( $c === 'a' || $c === 'O' ){"
"  $open = strpos($s, '{', $p);"
"  if( $open === false ){ return strlen($s); }"
"  $depth = 1;"
"  $i = $open + 1;"
"  $n = strlen($s);"
"  while( $i < $n && $depth > 0 ){"
"   $ch = $s[$i];"
"   if( $ch === 's' && substr($s, $i + 1, 1) === ':' ){"
"    /* skip strings wholesale so braces inside them don't count */"
"    $i = __sess_scan_fragment($s, $i);"
"    continue;"
"   }"
"   if( $ch === '{' ){ $depth++; }"
"   elseif( $ch === '}' ){ $depth--; }"
"   $i++;"
"  }"
"  return $i;"
" }"
" $e = strpos($s, ';', $p);"
" return $e === false ? strlen($s) : $e + 1;"
"}"
"function __sess_decode($s){"
" $out = [];"
" $p = 0;"
" $n = strlen($s);"
" while( $p < $n ){"
"  $bar = strpos($s, '|', $p);"
"  if( $bar === false ){ break; }"
"  $key = substr($s, $p, $bar - $p);"
"  $end = __sess_scan_fragment($s, $bar + 1);"
"  $frag = substr($s, $bar + 1, $end - ($bar + 1));"
"  $val = unserialize($frag);"
"  $out[$key] = $val;"
"  $p = $end;"
" }"
" return $out;"
"}"
"function __sess_encode($data){"
" $out = '';"
" foreach( $data as $k => $v ){"
"  $out .= $k . '|' . serialize($v);"
" }"
" return $out;"
"}"
"function session_start($options = []){"
" if( __SessS::$status === PHP_SESSION_ACTIVE ){"
"  trigger_error('session_start(): Ignoring session_start() because a session"
" is already active', E_USER_NOTICE);"
"  return true;"
" }"
" if( headers_sent() ){"
"  trigger_error('session_start(): Session cannot be started after headers have"
" already been sent', E_USER_WARNING);"
"  return false;"
" }"
" if( __SessS::$id === '' ){"
"  $n = __SessS::$name;"
"  if( isset($_COOKIE[$n]) && preg_match('/^[0-9a-zA-Z,-]{1,128}$/', $_COOKIE[$n]) ){"
"   __SessS::$id = $_COOKIE[$n];"
"  }else{"
"   __SessS::$id = __sess_genid();"
"  }"
" }"
" $file = __sess_file();"
" if( file_exists($file) ){"
"  $raw = file_get_contents($file);"
"  $_SESSION = is_string($raw) ? __sess_decode($raw) : [];"
" }else{"
"  $_SESSION = [];"
" }"
" __SessS::$status = PHP_SESSION_ACTIVE;"
" if( !__SessS::$wired ){"
"  __SessS::$wired = true;"
"  register_shutdown_function('session_write_close');"
"  if( function_exists('setcookie') ){"
"   setcookie(__SessS::$name, __SessS::$id);"
"  }"
" }"
" return true;"
"}"
"function session_write_close(){"
" if( __SessS::$status !== PHP_SESSION_ACTIVE ){ return false; }"
" file_put_contents(__sess_file(), __sess_encode($_SESSION));"
" __SessS::$status = PHP_SESSION_NONE;"
" return true;"
"}"
"function session_commit(){ return session_write_close(); }"
"function session_abort(){"
" if( __SessS::$status !== PHP_SESSION_ACTIVE ){ return false; }"
" __SessS::$status = PHP_SESSION_NONE;"
" return true;"
"}"
"function session_reset(){"
" if( __SessS::$status !== PHP_SESSION_ACTIVE ){ return false; }"
" $file = __sess_file();"
" $_SESSION = file_exists($file) ? __sess_decode(file_get_contents($file)) : [];"
" return true;"
"}"
"function session_unset(){"
" if( __SessS::$status !== PHP_SESSION_ACTIVE ){ return false; }"
" $_SESSION = [];"
" return true;"
"}"
"function session_destroy(){"
" if( __SessS::$status !== PHP_SESSION_ACTIVE ){"
"  trigger_error('session_destroy(): Trying to destroy uninitialized session',"
"   E_USER_WARNING);"
"  return false;"
" }"
" $file = __sess_file();"
" if( file_exists($file) ){ unlink($file); }"
" __SessS::$status = PHP_SESSION_NONE;"
" __SessS::$id = '';"
" return true;"
"}"
"function session_regenerate_id($deleteOldSession = false){"
" if( __SessS::$status !== PHP_SESSION_ACTIVE ){"
"  trigger_error('session_regenerate_id(): Session ID cannot be regenerated when"
" there is no active session', E_USER_WARNING);"
"  return false;"
" }"
" $oldFile = __sess_file();"
" if( $deleteOldSession && file_exists($oldFile) ){ unlink($oldFile); }"
" __SessS::$id = __sess_genid();"
" return true;"
"}"
;

PH7_PRIVATE sxi32 PH7_VmInstallSession(ph7_vm *pVm)
{
	return PH7_VmEvalBuiltinChunk(&(*pVm),zSessionLib,sizeof(zSessionLib)-1);
}

#endif /* PH7_DISABLE_DISK_IO */
#endif /* PH7_DISABLE_BUILTIN_FUNC */

#if defined(PH7_DISABLE_BUILTIN_FUNC) || defined(PH7_DISABLE_DISK_IO)
/* Tiny build: no sessions (builtin funcs / disk IO disabled) */
PH7_PRIVATE sxi32 PH7_VmInstallSession(ph7_vm *pVm){ (void)pVm; return SXRET_OK; }
#endif
