/**
 * SPDX-FileCopyrightText: 2011, 2012, 2013, 2014 Symisc Systems <licensing@symisc.net>
 * SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
 * SPDX-License-Identifier: BSD-3-Clause
 */
#include "ph7int.h"
/*
 * The embedded PHP source of the Reflection class library (chunks 1-9),
 * compiled at VM init by PH7_VmInstallReflectionLib() — the tail step of
 * PH7_VmInstallReflection() (vm_builtin_reflection.c, which keeps the C
 * host-function thunks the library calls).
 */
/*
 * Chunk 2: ReflectionFunctionAbstract, ReflectionFunction, ReflectionMethod,
 * ReflectionParameter.
 */
static const char zReflectLib2[] =
"abstract class ReflectionFunctionAbstract implements Reflector {"
" public $name;"
" protected $__cl = null;"
" protected function __rfinfo(){"
"  if($this->__cl !== null){ return __reflect_func_info($this->__cl); }"
"  return __reflect_func_info($this->name);"
" }"
" protected function __rftarget(){ return $this->__cl !== null ? $this->__cl : $this->name; }"
" protected function __rpspec(){ return $this->__rftarget(); }"
" public function getName(){ return $this->name; }"
" public function inNamespace(){ return strrpos($this->name,'\\\\') !== false; }"
" public function getNamespaceName(){"
"  $p = strrpos($this->name,'\\\\');"
"  if($p === false){ return ''; }"
"  return substr($this->name,0,$p);"
" }"
" public function getShortName(){"
"  $p = strrpos($this->name,'\\\\');"
"  if($p === false){ return $this->name; }"
"  return substr($this->name,$p+1);"
" }"
" public function isClosure(){ $i = $this->__rfinfo(); return $i['closure']; }"
" public function isGenerator(){ $i = $this->__rfinfo(); return $i['generator']; }"
" public function isVariadic(){ $i = $this->__rfinfo(); return $i['variadic']; }"
" public function returnsReference(){ $i = $this->__rfinfo(); return $i['byref']; }"
" public function isInternal(){ $i = $this->__rfinfo(); return $i['internal']; }"
" public function isUserDefined(){ return !$this->isInternal(); }"
" public function isDeprecated(){ $i = $this->__rfinfo(); return __reflect_has_deprecated($i['attrs']); }"
" public function isStatic(){ $i = $this->__rfinfo(); return $i['fstatic']; }"
" public function getFileName(){ $i = $this->__rfinfo(); return $i['file']; }"
" public function getStartLine(){"
"  $i = $this->__rfinfo();"
"  if($i['internal']){ return false; }"
"  return $i['line'];"
" }"
" public function getEndLine(){"
"  $i = $this->__rfinfo();"
"  if($i['internal']){ return false; }"
"  return $i['endline'];"
" }"
" public function getDocComment(){ $i = $this->__rfinfo(); return $i['doc']; }"
" public function hasReturnType(){ $i = $this->__rfinfo(); return $i['rettext'] !== null; }"
" public function getReturnType(){ $i = $this->__rfinfo(); return __reflect_make_type($i['rettext']); }"
" public function hasTentativeReturnType(){ return false; }"
" public function getTentativeReturnType(){ return null; }"
" public function getNumberOfParameters(){"
"  $i = $this->__rfinfo();"
"  if($i['minarg'] >= 0){ return $i['minarg']; }"
"  return count($i['params']);"
" }"
" public function getNumberOfRequiredParameters(){"
"  $i = $this->__rfinfo();"
"  if($i['minarg'] >= 0){ return $i['minarg']; }"
"  $req = 0;"
"  $n = count($i['params']);"
"  for($k = $n - 1; $k >= 0; $k--){"
"   $p = $i['params'][$k];"
"   if(!$p['variadic'] && !$p['hasdef']){ $req = $k + 1; break; }"
"  }"
"  return $req;"
" }"
" public function getParameters(){"
"  $i = $this->__rfinfo();"
"  $out = array();"
"  $spec = $this->__rpspec();"
"  foreach($i['params'] as $p){"
"   $out[] = new ReflectionParameter($spec, $p['pos']);"
"  }"
"  return $out;"
" }"
" public function getStaticVariables(){ $i = $this->__rfinfo(); return $i['statics']; }"
" public function getClosureThis(){"
"  $i = $this->__rfinfo();"
"  return isset($i['this']) ? $i['this'] : null;"
" }"
" public function getClosureScopeClass(){"
"  $i = $this->__rfinfo();"
"  if(isset($i['scope'])){ return new ReflectionClass($i['scope']); }"
"  if(isset($i['this'])){ return new ReflectionClass(get_class($i['this'])); }"
"  return null;"
" }"
" public function getClosureCalledClass(){ return $this->getClosureScopeClass(); }"
" public function getClosureUsedVariables(){"
"  $i = $this->__rfinfo();"
"  return isset($i['used']) ? $i['used'] : array();"
" }"
" public function getExtensionName(){ $i = $this->__rfinfo(); return $i['internal'] ? 'Core' : false; }"
" public function getExtension(){ $i = $this->__rfinfo(); return $i['internal'] ? new ReflectionExtension('Core') : null; }"
" public function getAttributes($name = null, $flags = 0){"
"  $i = $this->__rfinfo();"
"  if($this instanceof ReflectionMethod){"
"   $spec = array('method', $this->class, $this->name, 0);"
"   $target = 4;"
"  }else{"
"   $spec = array('fn', $this->__rftarget(), null, 0);"
"   $target = 2;"
"  }"
"  return __reflect_build_attrs($i['attrs'], $spec, $target, $name, $flags);"
" }"
" public function __toString(){ return __reflect_export_fnabs($this, ''); }"
"}"
"class ReflectionFunction extends ReflectionFunctionAbstract {"
" const IS_DEPRECATED = 2048;"
" public function __construct($function){"
"  if($function instanceof Closure){"
"   $this->__cl = $function;"
"   $i = $this->__rfinfo();"
"   if($i['closure']){"
"    $f = $i['file'] === false ? '' : $i['file'];"
"    $this->name = '{closure:'.$f.':'.$i['line'].'}';"
"   }else{"
"    $this->name = $i['name'];"
"   }"
"   return;"
"  }"
"  if(!is_string($function)){"
"   throw new TypeError('ReflectionFunction::__construct(): Argument #1 ($function) must be of type Closure|string, '.get_debug_type($function).' given');"
"  }"
"  $i = __reflect_func_info($function);"
"  if($i === null){"
"   throw new ReflectionException('Function '.$function.'() does not exist');"
"  }"
"  if($i['closure']){"
"   $this->name = '{closure:'.($i['file'] === false ? '' : $i['file']).':'.$i['line'].'}';"
"   $this->__cl = __reflect_closure($function, null, null);"
"  }else{"
"   $this->name = $i['name'];"
"  }"
" }"
" public function invoke(...$args){ return __reflect_invoke($this->__rftarget(), null, null, $args); }"
" public function invokeArgs(array $args){ return __reflect_invoke($this->__rftarget(), null, null, $args); }"
" public function getClosure(){"
"  if($this->__cl !== null){ return $this->__cl; }"
"  return __reflect_closure($this->name, null, null);"
" }"
" public function isAnonymous(){ $i = $this->__rfinfo(); return $i['closure']; }"
" public function isDisabled(){ return false; }"
"}"
"class ReflectionMethod extends ReflectionFunctionAbstract {"
" const IS_PUBLIC = 1;"
" const IS_PROTECTED = 2;"
" const IS_PRIVATE = 4;"
" const IS_STATIC = 16;"
" const IS_FINAL = 32;"
" const IS_ABSTRACT = 64;"
" public $class;"
" public function __construct($objectOrMethod, $method = null){"
"  if($method === null){"
"   if(!is_string($objectOrMethod) || strpos($objectOrMethod,'::') === false){"
"    throw new TypeError('ReflectionMethod::__construct(): Argument #1 ($objectOrMethod) must be of type object|string, '.get_debug_type($objectOrMethod).' given');"
"   }"
"   $p = strpos($objectOrMethod,'::');"
"   $method = substr($objectOrMethod,$p+2);"
"   $objectOrMethod = substr($objectOrMethod,0,$p);"
"  }"
"  $ci = __phl_rcinfo($objectOrMethod);"
"  if($ci === null){"
"   throw new ReflectionException('Class \"'.$objectOrMethod.'\" does not exist');"
"  }"
"  $this->class = $ci['name'];"
"  $found = null;"
"  if(isset($ci['methods'][$method])){"
"   $found = $method;"
"  }else{"
"   $l = strtolower($method);"
"   foreach($ci['methods'] as $k => $m){"
"    if(strtolower($k) === $l){ $found = $k; break; }"
"   }"
"  }"
"  if($found === null){"
"   throw new ReflectionException('Method '.$this->class.'::'.$method.'() does not exist');"
"  }"
"  $this->name = $found;"
" }"
" public static function createFromMethodName($name){"
"  return new ReflectionMethod($name);"
" }"
" protected function __rfinfo(){ return __reflect_func_info($this->class, $this->name); }"
" protected function __rpspec(){ return array($this->class, $this->name); }"
" public function getDeclaringClass(){"
"  $i = $this->__rfinfo();"
"  return new ReflectionClass($i['decl']);"
" }"
" public function getModifiers(){"
"  $i = $this->__rfinfo();"
"  $m = ($i['vis'] === 1 ? 1 : ($i['vis'] === 2 ? 2 : 4));"
"  if($i['mstatic']){ $m |= 16; }"
"  if($i['abstract']){ $m |= 64; }"
"  if($i['final']){ $m |= 32; }"
"  return $m;"
" }"
" public function isPublic(){ $i = $this->__rfinfo(); return $i['vis'] === 1; }"
" public function isProtected(){ $i = $this->__rfinfo(); return $i['vis'] === 2; }"
" public function isPrivate(){ $i = $this->__rfinfo(); return $i['vis'] === 3; }"
" public function isStatic(){ $i = $this->__rfinfo(); return $i['mstatic']; }"
" public function isAbstract(){ $i = $this->__rfinfo(); return $i['abstract']; }"
" public function isFinal(){ $i = $this->__rfinfo(); return $i['final']; }"
" public function isConstructor(){ return strtolower($this->name) === '__construct'; }"
" public function isDestructor(){ return strtolower($this->name) === '__destruct'; }"
" public function invoke($object = null, ...$args){ return $this->__rinvoke($object, $args); }"
" public function invokeArgs($object, array $args){ return $this->__rinvoke($object, $args); }"
" protected function __rinvoke($object, $args){"
"  $i = $this->__rfinfo();"
"  if(!$i['mstatic']){"
"   if(!is_object($object)){"
"    throw new ReflectionException('Trying to invoke non static method '.$this->class.'::'.$this->name.'() without an object');"
"   }"
"   if(!is_a($object, $i['decl'])){"
"    throw new ReflectionException('Given object is not an instance of the class this method was declared in');"
"   }"
"  }else{"
"   $object = null;"
"  }"
"  return __reflect_invoke($this->class, $this->name, $object, $args);"
" }"
" public function getClosure($object = null){"
"  $i = $this->__rfinfo();"
"  if(!$i['mstatic']){"
"   if($object === null){"
"    throw new ValueError('ReflectionMethod::getClosure(): Argument #1 ($object) cannot be null for non-static methods');"
"   }"
"   if(!is_a($object, $i['decl'])){"
"    throw new ReflectionException('Given object is not an instance of the class this method was declared in');"
"   }"
"  }else{"
"   $object = null;"
"  }"
"  return __reflect_closure($this->class, $this->name, $object);"
" }"
" public function setAccessible($accessible){ }"
" public function hasPrototype(){ return $this->__rproto() !== null; }"
" public function getPrototype(){"
"  $p = $this->__rproto();"
"  if($p === null){"
"   throw new ReflectionException('Method '.$this->class.'::'.$this->name.' does not have a prototype');"
"  }"
"  return new ReflectionMethod($p, $this->name);"
" }"
" protected function __rproto(){"
"  $ci = __phl_rcinfo($this->class);"
"  $l = strtolower($this->name);"
"  $p = $ci['parent'];"
"  while($p !== null){"
"   $pi = __phl_rcinfo($p);"
"   foreach($pi['methods'] as $k => $m){"
"    if(strtolower($k) === $l && $m['vis'] !== 3){ return $m['decl']; }"
"   }"
"   $p = $pi['parent'];"
"  }"
"  foreach($ci['interfaces'] as $if){"
"   $ii = __phl_rcinfo($if);"
"   foreach($ii['methods'] as $k => $m){"
"    if(strtolower($k) === $l){ return $ii['name']; }"
"   }"
"  }"
"  return null;"
" }"
" public function __toString(){ return __reflect_export_fnabs($this, ''); }"
"}"
"class ReflectionParameter implements Reflector {"
" public $name;"
" protected $__t;"
" protected $__m = null;"
" protected $__p = 0;"
" public function __construct($function, $param){"
"  $m = null;"
"  $t = $function;"
"  if(is_array($function)){"
"   $t = $function[0];"
"   $m = $function[1];"
"   if(is_object($t)){ $t = get_class($t); }"
"  }else if(is_string($function) && strpos($function,'::') !== false){"
"   $p = strpos($function,'::');"
"   $m = substr($function,$p+2);"
"   $t = substr($function,0,$p);"
"  }"
"  if($m !== null){"
"   $rm = new ReflectionMethod($t, $m);"
"   $t = $rm->class;"
"   $m = $rm->name;"
"   $i = __reflect_func_info($t, $m);"
"  }else if($function instanceof Closure){"
"   $t = $function;"
"   $i = __reflect_func_info($function);"
"  }else{"
"   $i = __reflect_func_info($t);"
"   if($i === null){"
"    throw new ReflectionException('Function '.$t.'() does not exist');"
"   }"
"  }"
"  $found = null;"
"  if(is_int($param)){"
"   if(isset($i['params'][$param])){ $found = $i['params'][$param]; }"
"   if($found === null){"
"    throw new ReflectionException('The parameter specified by its offset could not be found');"
"   }"
"  }else{"
"   foreach($i['params'] as $pp){"
"    if($pp['name'] === $param){ $found = $pp; break; }"
"   }"
"   if($found === null){"
"    throw new ReflectionException('The parameter specified by its name could not be found');"
"   }"
"  }"
"  $this->name = $found['name'];"
"  $this->__t = $t;"
"  $this->__m = $m;"
"  $this->__p = $found['pos'];"
" }"
" protected function __rffull(){"
"  if($this->__m !== null){ return __reflect_func_info($this->__t, $this->__m); }"
"  return __reflect_func_info($this->__t);"
" }"
" protected function __rpinfo(){"
"  $i = $this->__rffull();"
"  return $i['params'][$this->__p];"
" }"
" public function getName(){ return $this->name; }"
" public function getPosition(){ return $this->__p; }"
" public function isPassedByReference(){ $p = $this->__rpinfo(); return $p['byref']; }"
" public function canBePassedByValue(){ return !$this->isPassedByReference(); }"
" public function isVariadic(){ $p = $this->__rpinfo(); return $p['variadic']; }"
" public function isPromoted(){ $p = $this->__rpinfo(); return $p['promoted']; }"
" public function isDefaultValueAvailable(){ $p = $this->__rpinfo(); return $p['hasdef']; }"
" public function isOptional(){"
"  $i = $this->__rffull();"
"  $n = count($i['params']);"
"  for($k = $this->__p; $k < $n; $k++){"
"   $p = $i['params'][$k];"
"   if(!$p['variadic'] && !$p['hasdef'] && empty($p['optional'])){ return false; }"
"  }"
"  return true;"
" }"
" public function getDefaultValue(){"
"  if(!$this->isDefaultValueAvailable()){"
"   throw new ReflectionException('Internal error: Failed to retrieve the default value');"
"  }"
"  $p = $this->__rpinfo();"
"  if(isset($p['deftext'])){"
"   if($p['defscalar']){ return $p['defval']; }"
"   if($p['deftext'] === 'array (' || strpos($p['deftext'], '[') === 0){ return array(); }"
"   throw new ReflectionException('Internal error: Failed to retrieve the default value');"
"  }"
"  return __reflect_param_default($this->__t, $this->__m, $this->__p);"
" }"
" public function isDefaultValueConstant(){"
"  if(!$this->isDefaultValueAvailable()){ return false; }"
"  $p = $this->__rpinfo();"
"  if(isset($p['deftext'])){ return false; }"
"  return __reflect_param_defconst($this->__t, $this->__m, $this->__p) !== null;"
" }"
" public function getDefaultValueConstantName(){"
"  if(!$this->isDefaultValueAvailable()){"
"   throw new ReflectionException('Internal error: Failed to retrieve the default value');"
"  }"
"  return __reflect_param_defconst($this->__t, $this->__m, $this->__p);"
" }"
" public function allowsNull(){"
"  $p = $this->__rpinfo();"
"  if($p['typetext'] === null){ return true; }"
"  if($p['nullable']){ return true; }"
"  return $p['typetext'] === 'mixed' || $p['typetext'] === 'null';"
" }"
" public function hasType(){ $p = $this->__rpinfo(); return $p['typetext'] !== null; }"
" public function getType(){ $p = $this->__rpinfo(); return __reflect_make_type($p['typetext']); }"
" public function getDeclaringFunction(){"
"  if($this->__m !== null){ return new ReflectionMethod($this->__t, $this->__m); }"
"  return new ReflectionFunction($this->__t);"
" }"
" public function getDeclaringClass(){"
"  if($this->__m === null){ return null; }"
"  $i = $this->__rffull();"
"  return new ReflectionClass($i['decl']);"
" }"
" public function getAttributes($name = null, $flags = 0){"
"  $p = $this->__rpinfo();"
"  return __reflect_build_attrs($p['attrs'], array('param', $this->__t, $this->__m, $this->__p), 32, $name, $flags);"
" }"
" public function __toString(){ return __reflect_export_param($this); }"
"}"
;
/*
 * Chunk 3: PropertyHookType, ReflectionProperty, ReflectionClassConstant.
 */
static const char zReflectLib3[] =
"enum PropertyHookType: string {"
" case Get = 'get';"
" case Set = 'set';"
"}"
"class ReflectionProperty implements Reflector {"
" const IS_PUBLIC = 1;"
" const IS_PROTECTED = 2;"
" const IS_PRIVATE = 4;"
" const IS_STATIC = 16;"
" const IS_FINAL = 32;"
" const IS_ABSTRACT = 64;"
" const IS_READONLY = 128;"
" const IS_VIRTUAL = 512;"
" const IS_PROTECTED_SET = 2048;"
" const IS_PRIVATE_SET = 4096;"
" public $name;"
" public $class;"
" protected $__dynobj = null;"
" public function __construct($class, $property){"
"  $obj = null;"
"  if(is_object($class)){ $obj = $class; }"
"  else if(!is_string($class)){"
"   throw new TypeError('ReflectionProperty::__construct(): Argument #1 ($class) must be of type object|string, '.get_debug_type($class).' given');"
"  }"
"  $ci = __phl_rcinfo($class);"
"  if($ci === null){"
"   throw new ReflectionException('Class \"'.$class.'\" does not exist');"
"  }"
"  $this->class = $ci['name'];"
"  if(isset($ci['props'][$property])){"
"   $this->name = $property;"
"   return;"
"  }"
"  if($obj !== null && (__reflect_prop_state($obj, $property) & 1)){"
"   $this->name = $property;"
"   $this->__dynobj = $obj;"
"   return;"
"  }"
"  throw new ReflectionException('Property '.$this->class.'::$'.$property.' does not exist');"
" }"
" protected function __rpmeta(){"
"  $ci = __phl_rcinfo($this->class);"
"  if(isset($ci['props'][$this->name])){ return $ci['props'][$this->name]; }"
"  return array('vis' => 1, 'static' => false, 'readonly' => false, 'hasdef' => false,"
"   'typed' => false, 'typetext' => null, 'decl' => $this->class, 'line' => 0, 'dyn' => true);"
" }"
" public function getName(){ return $this->name; }"
" public function getDeclaringClass(){"
"  $m = $this->__rpmeta();"
"  return new ReflectionClass($m['decl']);"
" }"
" public function getModifiers(){"
"  $m = $this->__rpmeta();"
"  $mod = ($m['vis'] === 1 ? 1 : ($m['vis'] === 2 ? 2 : 4));"
"  if($m['static']){ $mod |= 16; }"
"  if($m['readonly']){ $mod |= 128; }"
"  return $mod;"
" }"
" public function isPublic(){ $m = $this->__rpmeta(); return $m['vis'] === 1; }"
" public function isProtected(){ $m = $this->__rpmeta(); return $m['vis'] === 2; }"
" public function isPrivate(){ $m = $this->__rpmeta(); return $m['vis'] === 3; }"
" public function isStatic(){ $m = $this->__rpmeta(); return $m['static']; }"
" public function isReadOnly(){ $m = $this->__rpmeta(); return $m['readonly']; }"
" public function isPrivateSet(){ $m = $this->__rpmeta(); return isset($m['privset']) ? $m['privset'] : false; }"
" public function isProtectedSet(){ $m = $this->__rpmeta(); return isset($m['protset']) ? $m['protset'] : false; }"
" public function isDefault(){ $m = $this->__rpmeta(); return !isset($m['dyn']); }"
" public function isDynamic(){ $m = $this->__rpmeta(); return isset($m['dyn']); }"
" public function isAbstract(){ return false; }"
" public function isFinal(){ return false; }"
" public function isVirtual(){ $m = $this->__rpmeta(); return isset($m['virtual']) ? $m['virtual'] : false; }"
" public function hasHooks(){ $m = $this->__rpmeta();"
"  return (isset($m['hookget']) && $m['hookget']) || (isset($m['hookset']) && $m['hookset']); }"
" public function getHooks(){"
"  $m = $this->__rpmeta(); $h = array();"
"  if(isset($m['hookget']) && $m['hookget']){ $h['get'] = new ReflectionMethod($m['decl'], '__phl_hook_get_'.$this->name); }"
"  if(isset($m['hookset']) && $m['hookset']){ $h['set'] = new ReflectionMethod($m['decl'], '__phl_hook_set_'.$this->name); }"
"  return $h; }"
" public function hasHook($type){"
"  $t = $type instanceof PropertyHookType ? $type->value : $type;"
"  $m = $this->__rpmeta();"
"  if($t === 'get'){ return isset($m['hookget']) && $m['hookget']; }"
"  if($t === 'set'){ return isset($m['hookset']) && $m['hookset']; }"
"  return false; }"
" public function getHook($type){"
"  $t = $type instanceof PropertyHookType ? $type->value : $type;"
"  $h = $this->getHooks();"
"  return isset($h[$t]) ? $h[$t] : null; }"
" public function isLazy($object){ return false; }"
" public function setAccessible($accessible){ }"
" public function getValue($object = null){"
"  $m = $this->__rpmeta();"
"  if($m['static']){ return __reflect_static_value($this->class, $this->name); }"
"  if(!is_object($object)){"
"   throw new ReflectionException('Instance of '.$this->class.' expected, but '.get_debug_type($object).' given');"
"  }"
"  return __reflect_prop_read($object, $this->name);"
" }"
" public function setValue($objectOrValue = null, $value = null){"
"  $m = $this->__rpmeta();"
"  if($m['static']){"
"   if($value === null && $objectOrValue !== null && !is_object($objectOrValue)){"
"    __reflect_static_set($this->class, $this->name, $objectOrValue);"
"   }else{"
"    __reflect_static_set($this->class, $this->name, $value);"
"   }"
"   return;"
"  }"
"  __reflect_prop_write($objectOrValue, $this->name, $value);"
" }"
" public function getRawValue($object){ return $this->getValue($object); }"
" public function setRawValue($object, $value){ $this->setValue($object, $value); }"
" public function isInitialized($object = null){"
"  $m = $this->__rpmeta();"
"  if($m['static']){ return (__reflect_prop_state($this->class, $this->name) & 2) !== 0; }"
"  if(!is_object($object)){"
"   throw new ReflectionException('Instance of '.$this->class.' expected, but '.get_debug_type($object).' given');"
"  }"
"  return (__reflect_prop_state($object, $this->name) & 2) !== 0;"
" }"
" public function hasDefaultValue(){"
"  $m = $this->__rpmeta();"
"  if(isset($m['dyn'])){ return false; }"
"  if($m['hasdef']){ return true; }"
"  return !$m['typed'];"
" }"
" public function getDefaultValue(){"
"  $m = $this->__rpmeta();"
"  if(isset($m['dyn']) || !$m['hasdef']){ return null; }"
"  return __reflect_prop_default($this->class, $this->name);"
" }"
" public function hasType(){ $m = $this->__rpmeta(); return $m['typed']; }"
" public function getType(){ $m = $this->__rpmeta(); return $m['typed'] ? __reflect_make_type($m['typetext']) : null; }"
" public function getSettableType(){ return $this->getType(); }"
" public function setRawValueWithoutLazyInitialization($object, $value){"
"  throw new Error('ReflectionProperty::setRawValueWithoutLazyInitialization() is not supported by PHL (no lazy objects)');"
" }"
" public function skipLazyInitialization($object){"
"  throw new Error('ReflectionProperty::skipLazyInitialization() is not supported by PHL (no lazy objects)');"
" }"
" public function getDocComment(){ $m = $this->__rpmeta(); return isset($m['doc']) ? $m['doc'] : false; }"
" public function getAttributes($name = null, $flags = 0){"
"  $m = $this->__rpmeta();"
"  if(!isset($m['attrs'])){ return array(); }"
"  return __reflect_build_attrs($m['attrs'], array('attr', $this->class, $this->name, 0), 8, $name, $flags);"
" }"
" public function __toString(){ return __reflect_export_prop($this); }"
"}"
"class ReflectionClassConstant implements Reflector {"
" const IS_PUBLIC = 1;"
" const IS_PROTECTED = 2;"
" const IS_PRIVATE = 4;"
" const IS_FINAL = 32;"
" public $name;"
" public $class;"
" public function __construct($class, $constant){"
"  if(!is_object($class) && !is_string($class)){"
"   throw new TypeError('ReflectionClassConstant::__construct(): Argument #1 ($class) must be of type object|string, '.get_debug_type($class).' given');"
"  }"
"  $ci = __phl_rcinfo($class);"
"  if($ci === null){"
"   throw new ReflectionException('Class \"'.$class.'\" does not exist');"
"  }"
"  $this->class = $ci['name'];"
"  if(!isset($ci['consts'][$constant])){"
"   throw new ReflectionException('Constant '.$this->class.'::'.$constant.' does not exist');"
"  }"
"  $this->name = $constant;"
" }"
" protected function __rcmeta(){"
"  $ci = __phl_rcinfo($this->class);"
"  return $ci['consts'][$this->name];"
" }"
" public function getName(){ return $this->name; }"
" public function getValue(){ return __reflect_const_value($this->class, $this->name); }"
" public function getDeclaringClass(){"
"  $m = $this->__rcmeta();"
"  return new ReflectionClass($m['decl']);"
" }"
" public function getModifiers(){"
"  $m = $this->__rcmeta();"
"  $mod = ($m['vis'] === 1 ? 1 : ($m['vis'] === 2 ? 2 : 4));"
"  if($m['final']){ $mod |= 32; }"
"  return $mod;"
" }"
" public function isPublic(){ $m = $this->__rcmeta(); return $m['vis'] === 1; }"
" public function isProtected(){ $m = $this->__rcmeta(); return $m['vis'] === 2; }"
" public function isPrivate(){ $m = $this->__rcmeta(); return $m['vis'] === 3; }"
" public function isFinal(){ $m = $this->__rcmeta(); return $m['final']; }"
" public function isEnumCase(){ $m = $this->__rcmeta(); return $m['enumcase']; }"
" public function isDeprecated(){ $m = $this->__rcmeta(); return __reflect_has_deprecated($m['attrs']); }"
" public function hasType(){ $m = $this->__rcmeta(); return $m['typed']; }"
" public function getType(){ $m = $this->__rcmeta(); return $m['typed'] ? __reflect_make_type($m['typetext']) : null; }"
" public function getDocComment(){ $m = $this->__rcmeta(); return $m['doc']; }"
" public function getAttributes($name = null, $flags = 0){"
"  $m = $this->__rcmeta();"
"  return __reflect_build_attrs($m['attrs'], array('attr', $this->class, $this->name, 0), 16, $name, $flags);"
" }"
" public function __toString(){ return __reflect_export_cconst($this); }"
"}"
;
/*
 * Chunk 6: the ReflectionEnum family. It is what is LEFT of the long tail --
 * ReflectionConstant, ReflectionExtension, ReflectionZendExtension and
 * ReflectionReference are native (PH7_VmInstallReflectionSmall). These three
 * stay because they extend ReflectionClass and ReflectionClassConstant, which
 * are still prelude PHP; they move when those do.
 */
static const char zReflectLib6[] =
"class ReflectionEnum extends ReflectionClass {"
" public function __construct($objectOrClass){"
"  $info = __phl_rcinfo($objectOrClass);"
"  if($info === null){"
"   throw new ReflectionException('Class \"'.$objectOrClass.'\" does not exist');"
"  }"
"  if(!$info['enum']){"
"   throw new ReflectionException('Class \"'.$info['name'].'\" is not an enum');"
"  }"
"  parent::__construct($objectOrClass);"
" }"
" public function hasCase($name){"
"  $i = __phl_rcinfo($this->name);"
"  return in_array($name, $i['cases'], true);"
" }"
" public function getCase($name){"
"  if(!$this->hasCase($name)){"
"   throw new ReflectionException('Case '.$this->name.'::'.$name.' does not exist');"
"  }"
"  if($this->isBacked()){ return new ReflectionEnumBackedCase($this->name, $name); }"
"  return new ReflectionEnumUnitCase($this->name, $name);"
" }"
" public function getCases(){"
"  $i = __phl_rcinfo($this->name);"
"  $out = array();"
"  foreach($i['cases'] as $c){"
"   $out[] = $this->isBacked()"
"    ? new ReflectionEnumBackedCase($this->name, $c)"
"    : new ReflectionEnumUnitCase($this->name, $c);"
"  }"
"  return $out;"
" }"
" public function isBacked(){ $i = __phl_rcinfo($this->name); return $i['enumbacking'] !== ''; }"
" public function getBackingType(){"
"  $i = __phl_rcinfo($this->name);"
"  if($i['enumbacking'] === ''){ return null; }"
"  return __reflect_make_type($i['enumbacking']);"
" }"
"}"
"class ReflectionEnumUnitCase extends ReflectionClassConstant {"
" public function __construct($class, $constant){"
"  parent::__construct($class, $constant);"
"  $ci = __phl_rcinfo($class);"
"  if(!$ci['enum']){"
"   throw new ReflectionException('Class \"'.$this->class.'\" is not an enum');"
"  }"
"  $m = $this->__rcmeta();"
"  if(!$m['enumcase']){"
"   throw new ReflectionException('Constant '.$this->class.'::'.$constant.' is not a case');"
"  }"
" }"
" public function getEnum(){ return new ReflectionEnum($this->class); }"
"}"
"class ReflectionEnumBackedCase extends ReflectionEnumUnitCase {"
" public function getBackingValue(){ return $this->getValue()->value; }"
"}"
;
/*
 * Chunk 7: ReflectionAttribute and the shared getAttributes() builder.
 * The spec array rides as [kind, target, member, paramIdx]; argument
 * values evaluate lazily through __reflect_attr_args (PHP semantics).
 */
static const char zReflectLib7[] =
"function __reflect_has_deprecated($meta){"
" foreach($meta as $a){"
"  if(strtolower($a['name']) === 'deprecated'){ return true; }"
" }"
" return false;"
"}"
"function __reflect_target_names($mask){"
" $parts = array();"
" foreach(array('class' => 1, 'function' => 2, 'method' => 4, 'property' => 8,"
"  'class constant' => 16, 'parameter' => 32, 'constant' => 64) as $nm => $bit){"
"  if($mask & $bit){ $parts[] = $nm; }"
" }"
" return implode(', ', $parts);"
"}"
"function __reflect_build_attrs($meta, $spec, $target, $name, $flags){"
" $out = array();"
" $counts = array();"
" foreach($meta as $a){"
"  $k = strtolower($a['name']);"
"  $counts[$k] = isset($counts[$k]) ? $counts[$k] + 1 : 1;"
" }"
" $idx = 0;"
" foreach($meta as $a){"
"  $keep = true;"
"  if($name !== null){"
"   $keep = strtolower($a['name']) === strtolower($name);"
"   if(!$keep && ($flags & 2)){"
"    $keep = is_subclass_of($a['name'], $name);"
"   }"
"  }"
"  if($keep){"
"   $r = __reflect_new_no_ctor('ReflectionAttribute');"
"   $r->__init($a['name'], $spec, $idx, $target, $counts[strtolower($a['name'])] > 1);"
"   $out[] = $r;"
"  }"
"  $idx++;"
" }"
" return $out;"
"}"
"final class ReflectionAttribute {"
" const IS_INSTANCEOF = 2;"
" protected $__name = '';"
" protected $__spec = null;"
" protected $__idx = 0;"
" protected $__target = 0;"
" protected $__rep = false;"
" public function __construct(){"
"  throw new Error('Call to private ReflectionAttribute::__construct() from global scope');"
" }"
" public function __init($name, $spec, $idx, $target, $rep){"
"  $this->__name = $name;"
"  $this->__spec = $spec;"
"  $this->__idx = $idx;"
"  $this->__target = $target;"
"  $this->__rep = $rep;"
" }"
" public function getName(){ return $this->__name; }"
" public function getTarget(){ return $this->__target; }"
" public function isRepeated(){ return $this->__rep; }"
" public function getArguments(){"
"  $a = __reflect_attr_args($this->__spec[0], $this->__spec[1], $this->__spec[2], $this->__spec[3], $this->__idx);"
"  return $a === null ? array() : $a;"
" }"
" public function newInstance(){"
"  $name = $this->__name;"
"  $ci = __phl_rcinfo($name);"
"  if($ci === null){"
"   throw new Error('Attribute class \"'.$name.'\" not found');"
"  }"
"  $name = $ci['name'];"
"  $decl = null;"
"  $didx = 0;"
"  foreach($ci['attrs'] as $a){"
"   if(strtolower($a['name']) === 'attribute'){ $decl = $didx; break; }"
"   $didx++;"
"  }"
"  if($decl === null){"
"   throw new Error('Attempting to use non-attribute class \"'.$name.'\" as attribute');"
"  }"
"  $dargs = __reflect_attr_args('class', $name, null, 0, $decl);"
"  $flags = 127;"
"  if(is_array($dargs)){"
"   if(isset($dargs[0])){ $flags = $dargs[0]; }"
"   else if(isset($dargs['flags'])){ $flags = $dargs['flags']; }"
"  }"
"  if(($flags & $this->__target) === 0){"
"   $tnames = array(1 => 'class', 2 => 'function', 4 => 'method', 8 => 'property',"
"    16 => 'class constant', 32 => 'parameter', 64 => 'constant');"
"   throw new Error('Attribute \"'.$name.'\" cannot target '.$tnames[$this->__target]"
"    .' (allowed targets: '.__reflect_target_names($flags).')');"
"  }"
"  if($this->__rep && ($flags & 128) === 0){"
"   throw new Error('Attribute \"'.$name.'\" must not be repeated');"
"  }"
"  return __reflect_new_instance($name, $this->getArguments());"
" }"
" public function __toString(){"
"  return 'Attribute [ '.$this->__name.' ]';"
" }"
"}"
;
/*
 * Chunk 9: PHP's Reflection export format (__toString on every Reflector).
 * Built entirely from the public reflection API of the target objects.
 */
static const char zReflectLib9[] =
"function __reflect_export_value($v){"
" if($v === null){ return 'NULL'; }"
" if($v === true){ return 'true'; }"
" if($v === false){ return 'false'; }"
" if(is_string($v)){ return chr(39).$v.chr(39); }"
" if(is_array($v)){"
"  $parts = array();"
"  $isList = true;"
"  $next = 0;"
"  foreach($v as $k => $x){"
"   if($k !== $next){ $isList = false; break; }"
"   $next++;"
"  }"
"  foreach($v as $k => $x){"
"   $parts[] = $isList ? __reflect_export_value($x)"
"    : (__reflect_export_value($k).' => '.__reflect_export_value($x));"
"  }"
"  return '['.implode(', ', $parts).']';"
" }"
" return (string)$v;"
"}"
"function __reflect_export_param($p){"
" $s = 'Parameter #'.$p->getPosition().' [ <'.($p->isOptional() ? 'optional' : 'required').'> ';"
" $t = $p->getType();"
" if($t !== null){ $s .= (string)$t.' '; }"
" if($p->isPassedByReference()){ $s .= '&'; }"
" if($p->isVariadic()){ $s .= '...'; }"
" $s .= '$'.$p->getName();"
" if($p->isDefaultValueAvailable()){"
"  try{ $s .= ' = '.__reflect_export_value($p->getDefaultValue()); }"
"  catch(ReflectionException $e){ $s .= ' = <default>'; }"
" }"
" return $s.' ]';"
"}"
"function __reflect_export_prop($p){"
" $s = 'Property [ ';"
" $s .= $p->isPrivate() ? 'private ' : ($p->isProtected() ? 'protected ' : 'public ');"
" if($p->isStatic()){ $s .= 'static '; }"
" if($p->isReadOnly()){ $s .= 'readonly '; }"
" $t = $p->getType();"
" if($t !== null){ $s .= (string)$t.' '; }"
" $s .= '$'.$p->getName();"
" if($p->hasDefaultValue()){ $s .= ' = '.__reflect_export_value($p->getDefaultValue()); }"
" return $s.' ]'.chr(10);"
"}"
"function __reflect_export_cconst($c){"
" $v = $c->getValue();"
" if(is_int($v)){ $t = 'int'; }"
" else if(is_string($v)){ $t = 'string'; }"
" else if(is_float($v)){ $t = 'float'; }"
" else if(is_bool($v)){ $t = 'bool'; }"
" else if(is_array($v)){ $t = 'array'; }"
" else{ $t = 'null'; }"
" $vs = is_array($v) ? 'Array' : (is_bool($v) ? ($v ? '1' : '') : (string)$v);"
" $vis = $c->isPrivate() ? 'private' : ($c->isProtected() ? 'protected' : 'public');"
" return 'Constant [ '.$vis.' '.$t.' '.$c->name.' ] { '.$vs.' }'.chr(10);"
"}"
"function __reflect_export_fnabs($r, $indent){"
" $tags = $r->isInternal() ? 'internal:Core' : 'user';"
" if($r instanceof ReflectionMethod){"
"  if($r->isConstructor()){ $tags .= ', ctor'; }"
"  else if($r->isDestructor()){ $tags .= ', dtor'; }"
"  $decl = $r->getDeclaringClass()->name;"
"  if(strtolower($decl) !== strtolower($r->class)){ $tags .= ', inherits '.$decl; }"
"  else if($r->hasPrototype()){ $tags .= ', prototype '.$r->getPrototype()->class; }"
"  $head = 'Method [ <'.$tags.'> ';"
"  if($r->isAbstract()){ $head .= 'abstract '; }"
"  if($r->isFinal()){ $head .= 'final '; }"
"  if($r->isStatic()){ $head .= 'static '; }"
"  $head .= $r->isPrivate() ? 'private ' : ($r->isProtected() ? 'protected ' : 'public ');"
"  $head .= 'method '.$r->name.' ]';"
" }else{"
"  $kind = $r->isClosure() ? 'Closure' : 'Function';"
"  $head = $kind.' [ <'.$tags.'> function '.$r->name.' ]';"
" }"
" $s = $head.' {'.chr(10);"
" if(!$r->isInternal()){"
"  $s .= '  @@ '.$r->getFileName().' '.$r->getStartLine().' - '.$r->getEndLine().chr(10);"
" }"
" $ps = $r->getParameters();"
" $ret = $r->getReturnType();"
" if(count($ps) > 0 || $ret !== null){"
"  $s .= chr(10).'  - Parameters ['.count($ps).'] {'.chr(10);"
"  foreach($ps as $p){ $s .= '    '.__reflect_export_param($p).chr(10); }"
"  $s .= '  }'.chr(10);"
" }"
" if($ret !== null){ $s .= '  - Return [ '.(string)$ret.' ]'.chr(10); }"
" $s .= '}'.chr(10);"
" if($indent === ''){ return $s; }"
" $lines = explode(chr(10), $s);"
" $out = '';"
" $n = count($lines);"
" for($k = 0; $k < $n; $k++){"
"  if($lines[$k] === '' && $k === $n - 1){ break; }"
"  $out .= ($lines[$k] === '' ? '' : $indent.$lines[$k]).chr(10);"
" }"
" return $out;"
"}"
"function __reflect_export_class($rc){"
" $tags = $rc->isInternal() ? 'internal:Core' : 'user';"
" if($rc->isInterface()){"
"  $head = 'Interface [ <'.$tags.'> interface '.$rc->name.' ]';"
" }else{"
"  $mods = '';"
"  if($rc->isAbstract()){ $mods .= 'abstract '; }"
"  if($rc->isFinal()){ $mods .= 'final '; }"
"  $head = 'Class [ <'.$tags.'> '.$mods.'class '.$rc->name;"
"  $par = $rc->getParentClass();"
"  if($par !== false){ $head .= ' extends '.$par->name; }"
"  $ifs = $rc->getInterfaceNames();"
"  if(count($ifs) > 0){ $head .= ' implements '.implode(', ', $ifs); }"
"  $head .= ' ]';"
" }"
" $s = $head.' {'.chr(10);"
" if(!$rc->isInternal()){"
"  $s .= '  @@ '.$rc->getFileName().' '.$rc->getStartLine().'-'.$rc->getEndLine().chr(10);"
" }"
" $consts = $rc->getReflectionConstants();"
" $s .= chr(10).'  - Constants ['.count($consts).'] {'.chr(10);"
" foreach($consts as $c){ $s .= '    '.__reflect_export_cconst($c); }"
" $s .= '  }'.chr(10);"
" $sp = array();"
" $ip = array();"
" foreach($rc->getProperties() as $p){"
"  if($p->isStatic()){ $sp[] = $p; }else{ $ip[] = $p; }"
" }"
" $sm = array();"
" $im = array();"
" foreach($rc->getMethods() as $m){"
"  if($m->isStatic()){ $sm[] = $m; }else{ $im[] = $m; }"
" }"
" $s .= chr(10).'  - Static properties ['.count($sp).'] {'.chr(10);"
" foreach($sp as $p){ $s .= '    '.__reflect_export_prop($p); }"
" $s .= '  }'.chr(10);"
" $s .= chr(10).'  - Static methods ['.count($sm).'] {'.chr(10);"
" $first = true;"
" foreach($sm as $m){"
"  if(!$first){ $s .= chr(10); }"
"  $first = false;"
"  $s .= __reflect_export_fnabs($m, '    ');"
" }"
" $s .= '  }'.chr(10);"
" $s .= chr(10).'  - Properties ['.count($ip).'] {'.chr(10);"
" foreach($ip as $p){ $s .= '    '.__reflect_export_prop($p); }"
" $s .= '  }'.chr(10);"
" $s .= chr(10).'  - Methods ['.count($im).'] {'.chr(10);"
" $first = true;"
" foreach($im as $m){"
"  if(!$first){ $s .= chr(10); }"
"  $first = false;"
"  $s .= __reflect_export_fnabs($m, '    ');"
" }"
" $s .= '  }'.chr(10);"
" return $s.'}'.chr(10);"
"}"
;
/*
 * Register the __reflect_* thunks and compile the Reflection library.
 * Called from PH7_VmInit while pVm->bCompilingBuiltin is set, right after
 * the core builtin chunks (Exception and friends must exist already).
 */
/*
 * Compile the nine reflection chunks, in order. Split from
 * PH7_VmInstallReflection so the chunk strings and their sizeof stay in
 * one translation unit.
 */
PH7_PRIVATE sxi32 PH7_VmInstallReflectionLib(ph7_vm *pVm)
{
	sxi32 rc;
	/* Where chunk 1 was: Reflector, Reflection, ReflectionException,
	 * ReflectionClass and ReflectionObject are native now. Chunks 2 and 3 name
	 * `Reflector` in their own `implements` clauses, so this has to run first. */
	rc = PH7_VmInstallReflectionClass(&(*pVm));
	if( rc != SXRET_OK ){
		return rc;
	}
	rc = PH7_VmEvalBuiltinChunk(&(*pVm), zReflectLib2, sizeof(zReflectLib2)-1);
	if( rc != SXRET_OK ){
		return rc;
	}
	rc = PH7_VmEvalBuiltinChunk(&(*pVm), zReflectLib3, sizeof(zReflectLib3)-1);
	if( rc != SXRET_OK ){
		return rc;
	}
	/* Where chunk 4 was: the four type classes are native now (see
	 * PH7_VmInstallReflectionTypes). Stringable exists by this point. */
	rc = PH7_VmInstallReflectionTypes(&(*pVm));
	if( rc != SXRET_OK ){
		return rc;
	}
	/* Where chunk 5 was: ReflectionGenerator/Fiber and the four standalone
	 * classes chunk 6 used to hold are native now. Reflector (chunk 1) exists. */
	rc = PH7_VmInstallReflectionSmall(&(*pVm));
	if( rc != SXRET_OK ){
		return rc;
	}
	rc = PH7_VmEvalBuiltinChunk(&(*pVm), zReflectLib6, sizeof(zReflectLib6)-1);
	if( rc != SXRET_OK ){
		return rc;
	}
	rc = PH7_VmEvalBuiltinChunk(&(*pVm), zReflectLib7, sizeof(zReflectLib7)-1);
	if( rc != SXRET_OK ){
		return rc;
	}
	return PH7_VmEvalBuiltinChunk(&(*pVm), zReflectLib9, sizeof(zReflectLib9)-1);
}
