/**
 * SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
 * SPDX-License-Identifier: BSD-3-Clause
 */
#include "ph7int.h"
#ifndef PH7_DISABLE_BUILTIN_FUNC
/*
 * SPL iterators, slice 1 (NEWPLAN band D): SeekableIterator, ArrayIterator,
 * ArrayObject, plus the natsort()/natcasesort() array functions they need.
 * Embedded-PHP chunk following the Reflection architecture — installed
 * inside the bCompilingBuiltin window, backed by the engine's native array
 * internal-pointer builtins (reset/next/key/current keep their position on a
 * property, so ArrayIterator's cursor IS the backing array's pointer).
 */

/* void __spl_deprecated(string $msg) — E_DEPRECATED with php's exact text
 * (no auto-prepended function name, unlike ph7_context_throw_error) */
static int vm_builtin_spl_deprecated(ph7_context *pCtx,int nArg,ph7_value **apArg)
{
	const char *zMsg;
	int nMsg;
	if( nArg < 1 ){
		return PH7_OK;
	}
	zMsg = ph7_value_to_string(apArg[0],&nMsg);
	PH7_VmThrowDeprecatedFmt(pCtx->pVm,"%.*s",nMsg,zMsg);
	return PH7_OK;
}

static const char zSplLib[] =
"interface SeekableIterator extends Iterator {"
" public function seek($offset);"
"}"
"trait __SplStoreT {"
" private $__d = [];"
" private $__f = 0;"
" private function __splInitStore($array, $flags, $ctor){"
"  if( is_array($array) ){"
"   $this->__d = $array;"
"  }elseif( is_object($array) ){"
"   __spl_deprecated(get_class($this) . '::' . $ctor . '(): Using an object as a"
" backing array for ' . get_class($this) . ' is deprecated, as it allows violating"
" class constraints and invariants');"
"  $this->__d = get_object_vars($array);"
"  }else{"
"   throw new TypeError(get_class($this) . '::' . $ctor . '(): Argument #1 ($array)"
" must be of type array, ' . get_debug_type($array) . ' given');"
"  }"
"  $this->__f = (int)$flags;"
" }"
" public function offsetExists($key){ return array_key_exists($key, $this->__d); }"
" public function offsetGet($key){ return $this->__d[$key]; }"
" public function offsetSet($key, $value){"
"  if( $key === null ){ $this->__d[] = $value; }"
"  else { $this->__d[$key] = $value; }"
" }"
" public function offsetUnset($key){ unset($this->__d[$key]); }"
" public function append($value){ $this->__d[] = $value; }"
" public function getArrayCopy(){ return $this->__d; }"
" public function count(){ return count($this->__d); }"
" public function getFlags(){ return $this->__f; }"
" public function setFlags($flags){ $this->__f = (int)$flags; }"
" public function asort($flags = 0){ asort($this->__d); return true; }"
" public function ksort($flags = 0){ ksort($this->__d); return true; }"
" public function uasort($callback){ uasort($this->__d, $callback); return true; }"
" public function uksort($callback){ uksort($this->__d, $callback); return true; }"
" public function natsort(){ uasort($this->__d, 'strnatcmp'); return true; }"
" public function natcasesort(){ uasort($this->__d, 'strnatcasecmp'); return true; }"
"}"
"class ArrayIterator implements SeekableIterator, ArrayAccess, Countable {"
" use __SplStoreT;"
" const STD_PROP_LIST = 1;"
" const ARRAY_AS_PROPS = 2;"
" public function __construct($array = [], $flags = 0){"
"  $this->__splInitStore($array, $flags, '__construct');"
"  reset($this->__d);"
" }"
" public function current(){"
"  if( key($this->__d) === null ){ return null; }"
"  return current($this->__d);"
" }"
" public function key(){ return key($this->__d); }"
" public function next(){ next($this->__d); }"
" public function rewind(){ reset($this->__d); }"
" public function valid(){ return key($this->__d) !== null; }"
" public function seek($offset){"
"  $offset = (int)$offset;"
"  if( $offset < 0 || $offset >= count($this->__d) ){"
"   throw new OutOfBoundsException('Seek position ' . $offset . ' is out of range');"
"  }"
"  reset($this->__d);"
"  for( $i = 0; $i < $offset; $i++ ){ next($this->__d); }"
" }"
"}"
"class ArrayObject implements IteratorAggregate, ArrayAccess, Countable {"
" use __SplStoreT;"
" const STD_PROP_LIST = 1;"
" const ARRAY_AS_PROPS = 2;"
" private $__it = 'ArrayIterator';"
" public function __construct($array = [], $flags = 0, $iteratorClass = 'ArrayIterator'){"
"  $this->__splInitStore($array, $flags, '__construct');"
"  if( $iteratorClass !== 'ArrayIterator' ){ $this->setIteratorClass($iteratorClass); }"
" }"
" public function getIterator(){"
"  $c = $this->__it;"
"  return new $c($this->__d);"
" }"
" public function exchangeArray($array){"
"  $old = $this->__d;"
"  $this->__splInitStore($array, $this->__f, 'exchangeArray');"
"  return $old;"
" }"
" public function setIteratorClass($iteratorClass){"
"  $c = (string)$iteratorClass;"
"  if( $c !== 'ArrayIterator'"
"   && (!class_exists($c) || !is_subclass_of($c, 'ArrayIterator')) ){"
"   throw new TypeError('ArrayObject::setIteratorClass(): Argument #1"
" ($iteratorClass) must be a class name derived from ArrayIterator, ' . $c . ' given');"
"  }"
"  $this->__it = $c;"
" }"
" public function getIteratorClass(){ return $this->__it; }"
" public function __get($name){"
"  if( $this->__f & 2 ){ return $this->__d[$name]; }"
"  return null;"
" }"
" public function __set($name, $value){"
"  if( $this->__f & 2 ){ $this->__d[$name] = $value; return; }"
"  $this->{$name} = $value;"
" }"
" public function __isset($name){"
"  if( $this->__f & 2 ){ return isset($this->__d[$name]); }"
"  return false;"
" }"
" public function __unset($name){"
"  if( $this->__f & 2 ){ unset($this->__d[$name]); }"
" }"
"}"
"function natsort(&$array){ return uasort($array, 'strnatcmp'); }"
"function natcasesort(&$array){ return uasort($array, 'strnatcasecmp'); }"
"interface OuterIterator extends Iterator {"
" public function getInnerIterator();"
"}"
"class IteratorIterator implements OuterIterator {"
" private $__in = null;"
" public function __construct($iterator, $class = null){"
"  while( $iterator instanceof IteratorAggregate ){ $iterator = $iterator->getIterator(); }"
"  if( !($iterator instanceof Iterator) ){"
"   throw new TypeError(get_class($this) . '::__construct(): Argument #1 ($iterator)"
" must be of type Traversable, ' . get_debug_type($iterator) . ' given');"
"  }"
"  $this->__in = $iterator;"
" }"
" public function getInnerIterator(){ return $this->__in; }"
" public function current(){ return $this->__in->current(); }"
" public function key(){ return $this->__in->key(); }"
" public function next(){ $this->__in->next(); }"
" public function rewind(){ $this->__in->rewind(); }"
" public function valid(){ return $this->__in->valid(); }"
"}"
"class LimitIterator extends IteratorIterator {"
" private $__off = 0;"
" private $__lim = -1;"
" private $__pos = 0;"
" public function __construct($iterator, $offset = 0, $limit = -1){"
"  $offset = (int)$offset; $limit = (int)$limit;"
"  if( $offset < 0 ){"
"   throw new ValueError('LimitIterator::__construct(): Argument #2 ($offset) must be"
" greater than or equal to 0');"
"  }"
"  if( $limit < -1 ){"
"   throw new ValueError('LimitIterator::__construct(): Argument #3 ($limit) must be"
" greater than or equal to -1');"
"  }"
"  parent::__construct($iterator);"
"  $this->__off = $offset;"
"  $this->__lim = $limit;"
" }"
" public function rewind(){"
"  $in = $this->getInnerIterator();"
"  $in->rewind();"
"  for( $i = 0; $i < $this->__off && $in->valid(); $i++ ){ $in->next(); }"
"  $this->__pos = $this->__off;"
" }"
" public function valid(){"
"  if( $this->__lim != -1 && $this->__pos >= $this->__off + $this->__lim ){ return false; }"
"  return $this->getInnerIterator()->valid();"
" }"
" public function next(){ $this->__pos++; $this->getInnerIterator()->next(); }"
" public function getPosition(){ return $this->__pos; }"
" public function seek($offset){"
"  $offset = (int)$offset;"
"  if( $offset < $this->__off ){"
"   throw new OutOfBoundsException('Cannot seek to ' . $offset . ' which is below the"
" offset ' . $this->__off);"
"  }"
"  if( $this->__lim != -1 && $offset >= $this->__off + $this->__lim ){"
"   throw new OutOfBoundsException('Cannot seek to ' . $offset . ' which is behind or"
" equal to the limit ' . $this->__lim . ' plus the offset ' . $this->__off);"
"  }"
"  $in = $this->getInnerIterator();"
"  $in->rewind();"
"  for( $i = 0; $i < $offset && $in->valid(); $i++ ){ $in->next(); }"
"  $this->__pos = $offset;"
"  return $this->__pos;"
" }"
"}"
"abstract class FilterIterator extends IteratorIterator {"
" abstract public function accept();"
" private function __fiFetch(){"
"  $in = $this->getInnerIterator();"
"  while( $in->valid() && !$this->accept() ){ $in->next(); }"
" }"
" public function rewind(){ $this->getInnerIterator()->rewind(); $this->__fiFetch(); }"
" public function next(){ $this->getInnerIterator()->next(); $this->__fiFetch(); }"
"}"
"class CallbackFilterIterator extends FilterIterator {"
" private $__cb = null;"
" public function __construct($iterator, $callback){"
"  parent::__construct($iterator);"
"  $this->__cb = $callback;"
" }"
" public function accept(){"
"  $in = $this->getInnerIterator();"
"  return (bool)call_user_func($this->__cb, $in->current(), $in->key(), $in);"
" }"
"}"
"class RegexIterator extends FilterIterator {"
" const USE_KEY = 1;"
" const INVERT_MATCH = 2;"
" const MATCH = 0;"
" const GET_MATCH = 1;"
" const ALL_MATCHES = 2;"
" const SPLIT = 3;"
" const REPLACE = 4;"
" public $replacement = null;"
" private $__re = '';"
" private $__mode = 0;"
" private $__rflags = 0;"
" private $__pflags = 0;"
" private $__cur = null;"
" public function __construct($iterator, $pattern, $mode = 0, $flags = 0, $pregFlags = 0){"
"  parent::__construct($iterator);"
"  $this->__re = (string)$pattern;"
"  $this->__mode = (int)$mode;"
"  $this->__rflags = (int)$flags;"
"  $this->__pflags = (int)$pregFlags;"
" }"
" public function accept(){"
"  $in = $this->getInnerIterator();"
"  if( !$in->valid() ){ return false; }"
"  $subject = ($this->__rflags & self::USE_KEY) ? $in->key() : $in->current();"
"  $subject = (string)$subject;"
"  $this->__cur = null;"
"  $ok = false;"
"  if( $this->__mode === self::MATCH ){"
"   $ok = preg_match($this->__re, $subject) > 0;"
"  }elseif( $this->__mode === self::GET_MATCH ){"
"   $m = null;"
"   $ok = preg_match($this->__re, $subject, $m, $this->__pflags) > 0;"
"   $this->__cur = $m;"
"  }elseif( $this->__mode === self::ALL_MATCHES ){"
"   $m = null;"
"   $ok = preg_match_all($this->__re, $subject, $m, $this->__pflags) > 0;"
"   $this->__cur = $m;"
"  }elseif( $this->__mode === self::SPLIT ){"
"   $this->__cur = preg_split($this->__re, $subject, -1, $this->__pflags);"
"   $ok = is_array($this->__cur) && count($this->__cur) > 1;"
"  }elseif( $this->__mode === self::REPLACE ){"
"   $n = 0;"
"   $this->__cur = preg_replace($this->__re, (string)$this->replacement, $subject, -1, $n);"
"   $ok = $n > 0;"
"  }"
"  if( $this->__rflags & self::INVERT_MATCH ){ $ok = !$ok; }"
"  return $ok;"
" }"
" public function current(){"
"  if( $this->__mode === self::MATCH ){ return $this->getInnerIterator()->current(); }"
"  return $this->__cur;"
" }"
" public function getRegex(){ return $this->__re; }"
" public function getMode(){ return $this->__mode; }"
" public function setMode($mode){ $this->__mode = (int)$mode; }"
" public function getFlags(){ return $this->__rflags; }"
" public function setFlags($flags){ $this->__rflags = (int)$flags; }"
" public function getPregFlags(){ return $this->__pflags; }"
" public function setPregFlags($pregFlags){ $this->__pflags = (int)$pregFlags; }"
"}"
"class AppendIterator implements OuterIterator {"
" private $__its = [];"
" private $__idx = 0;"
" public function __construct(){}"
" public function append($iterator){"
"  $this->__its[] = $iterator;"
"  if( count($this->__its) === 1 ){ $iterator->rewind(); }"
" }"
" public function getInnerIterator(){ return $this->__its[$this->__idx] ?? null; }"
" public function getIteratorIndex(){"
"  return isset($this->__its[$this->__idx]) ? $this->__idx : null;"
" }"
" public function getArrayIterator(){ return new ArrayIterator($this->__its); }"
" private function __apAdvance(){"
"  while( isset($this->__its[$this->__idx])"
"   && !$this->__its[$this->__idx]->valid()"
"   && isset($this->__its[$this->__idx + 1]) ){"
"   $this->__idx++;"
"   $this->__its[$this->__idx]->rewind();"
"  }"
" }"
" public function rewind(){"
"  $this->__idx = 0;"
"  if( isset($this->__its[0]) ){ $this->__its[0]->rewind(); }"
"  $this->__apAdvance();"
" }"
" public function valid(){"
"  $in = $this->getInnerIterator();"
"  return $in !== null && $in->valid();"
" }"
" public function current(){ $in = $this->getInnerIterator(); return $in ? $in->current() : null; }"
" public function key(){ $in = $this->getInnerIterator(); return $in ? $in->key() : null; }"
" public function next(){"
"  $in = $this->getInnerIterator();"
"  if( $in ){ $in->next(); }"
"  $this->__apAdvance();"
" }"
"}"
"class InfiniteIterator extends IteratorIterator {"
" public function next(){"
"  $in = $this->getInnerIterator();"
"  $in->next();"
"  if( !$in->valid() ){ $in->rewind(); }"
" }"
"}"
"class NoRewindIterator extends IteratorIterator {"
" public function rewind(){}"
"}"
"class EmptyIterator implements Iterator {"
" public function current(){"
"  throw new BadMethodCallException('Accessing the value of an EmptyIterator');"
" }"
" public function key(){"
"  throw new BadMethodCallException('Accessing the key of an EmptyIterator');"
" }"
" public function next(){}"
" public function rewind(){}"
" public function valid(){ return false; }"
"}"
;

PH7_PRIVATE sxi32 PH7_VmInstallSpl(ph7_vm *pVm)
{
	ph7_create_function(&(*pVm),"__spl_deprecated",vm_builtin_spl_deprecated,0);
	return PH7_VmEvalBuiltinChunk(&(*pVm),zSplLib,sizeof(zSplLib)-1);
}

#endif /* PH7_DISABLE_BUILTIN_FUNC */

#ifdef PH7_DISABLE_BUILTIN_FUNC
/* Tiny build: no SPL (builtin layer disabled) */
PH7_PRIVATE sxi32 PH7_VmInstallSpl(ph7_vm *pVm){ (void)pVm; return SXRET_OK; }
#endif
