/**
 * SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
 * SPDX-License-Identifier: BSD-3-Clause
 */
#include "ph7int.h"
#ifndef PH7_DISABLE_BUILTIN_FUNC
/*
 * SPL iterators, slice 1 (NEWPLAN band D): SeekableIterator, ArrayIterator,
 * ArrayObject, plus the natsort()/natcasesort() array functions they need.
 * Embedded-PHP chunk following the Reflection architecture — installed
 * inside the bCompilingBuiltin window, backed by the engine's native array
 * internal-pointer builtins (reset/next/key/current keep their position on a
 * property, so ArrayIterator's cursor IS the backing array's pointer).
 */

/* void __spl_deprecated(string $msg) — E_DEPRECATED with php's exact text
 * (no auto-prepended function name, unlike ph7_context_throw_error) */
static int vm_builtin_spl_deprecated(ph7_context *pCtx,int nArg,ph7_value **apArg)
{
	const char *zMsg;
	int nMsg;
	if( nArg < 1 ){
		return PH7_OK;
	}
	zMsg = ph7_value_to_string(apArg[0],&nMsg);
	PH7_VmThrowDeprecatedFmt(pCtx->pVm,"%.*s",nMsg,zMsg);
	return PH7_OK;
}

/* int __weak_create(object $obj) — register/share the weak cell for $obj,
 * returning the cell pointer as an opaque int handle */
static int vm_builtin_weak_create(ph7_context *pCtx,int nArg,ph7_value **apArg)
{
	ph7_vm *pVm = pCtx->pVm;
	ph7_class_instance *pObj;
	VmWeakCell *pCell = 0;
	SyHashEntry *pEntry;
	if( nArg < 1 || (apArg[0]->iFlags & MEMOBJ_OBJ) == 0 ){
		ph7_result_int(pCtx,0);
		return PH7_OK;
	}
	pObj = (ph7_class_instance *)apArg[0]->x.pOther;
	pEntry = SyHashGet(&pVm->hWeakCell,(const void *)&pObj,sizeof(void *));
	if( pEntry ){
		pCell = (VmWeakCell *)pEntry->pUserData;
		pCell->nRef++;
	}else{
		pCell = (VmWeakCell *)SyMemBackendAlloc(&pVm->sAllocator,sizeof(VmWeakCell));
		if( pCell == 0 ){
			return PH7_ContextMemoryError(pCtx);
		}
		pCell->pObj = pObj;
		pCell->nRef = 1;
		/* SyHash stores the key POINTER (no copy): key off the cell's own
		 * pObj field — heap-stable for the entry's whole lifetime, and it
		 * holds the live pointer bytes until the release hook nulls it
		 * (which happens only after the entry is deleted). */
		if( SyHashInsert(&pVm->hWeakCell,(const void *)&pCell->pObj,sizeof(void *),pCell) != SXRET_OK ){
			SyMemBackendFree(&pVm->sAllocator,pCell);
			return PH7_ContextMemoryError(pCtx);
		}
	}
	ph7_result_int64(pCtx,(ph7_int64)(sxu64)(sxuptr)pCell);
	return PH7_OK;
}
/* ?object __weak_get(int $handle) — the target instance, or null once dead */
static int vm_builtin_weak_get(ph7_context *pCtx,int nArg,ph7_value **apArg)
{
	VmWeakCell *pCell;
	if( nArg < 1 ){
		ph7_result_null(pCtx);
		return PH7_OK;
	}
	pCell = (VmWeakCell *)(sxuptr)(sxu64)ph7_value_to_int64(apArg[0]);
	if( pCell == 0 || pCell->pObj == 0 ){
		ph7_result_null(pCtx);
		return PH7_OK;
	}
	{
		/* Hand the instance back: ph7_result_value's MemObjStore takes the
		 * reference, so the temp holds none of its own. */
		ph7_value sObj;
		PH7_MemObjInit(pCtx->pVm,&sObj);
		sObj.x.pOther = pCell->pObj;
		MemObjSetType(&sObj,MEMOBJ_OBJ);
		ph7_result_value(pCtx,&sObj);
	}
	return PH7_OK;
}
/* void __weak_drop(int $handle) — release one PHP-side handle */
static int vm_builtin_weak_drop(ph7_context *pCtx,int nArg,ph7_value **apArg)
{
	ph7_vm *pVm = pCtx->pVm;
	VmWeakCell *pCell;
	if( nArg < 1 ){
		return PH7_OK;
	}
	pCell = (VmWeakCell *)(sxuptr)(sxu64)ph7_value_to_int64(apArg[0]);
	if( pCell == 0 || pCell->nRef == 0 ){
		return PH7_OK;
	}
	pCell->nRef--;
	if( pCell->nRef == 0 ){
		if( pCell->pObj ){
			/* Still alive: unhook the registry entry before freeing */
			void *pDummy = 0;
			SyHashDeleteEntry(&pVm->hWeakCell,(const void *)&pCell->pObj,sizeof(void *),&pDummy);
		}
		SyMemBackendFree(&pVm->sAllocator,pCell);
	}
	return PH7_OK;
}

static const char zSplLib[] =
"interface SeekableIterator extends Iterator {"
" public function seek($offset);"
"}"
"trait __SplStoreT {"
" private $__d = [];"
" private $__f = 0;"
" private function __splInitStore($array, $flags, $ctor){"
"  if( is_array($array) ){"
"   $this->__d = $array;"
"  }elseif( is_object($array) ){"
"   __spl_deprecated(get_class($this) . '::' . $ctor . '(): Using an object as a"
" backing array for ' . get_class($this) . ' is deprecated, as it allows violating"
" class constraints and invariants');"
"  $this->__d = get_object_vars($array);"
"  }else{"
"   throw new TypeError(get_class($this) . '::' . $ctor . '(): Argument #1 ($array)"
" must be of type array, ' . get_debug_type($array) . ' given');"
"  }"
"  $this->__f = (int)$flags;"
" }"
" public function offsetExists($key){ return array_key_exists($key, $this->__d); }"
" public function offsetGet($key){ return $this->__d[$key]; }"
" public function offsetSet($key, $value){"
"  if( $key === null ){ $this->__d[] = $value; }"
"  else { $this->__d[$key] = $value; }"
" }"
" public function offsetUnset($key){ unset($this->__d[$key]); }"
" public function append($value){ $this->__d[] = $value; }"
" public function getArrayCopy(){ return $this->__d; }"
" public function count(){ return count($this->__d); }"
" public function getFlags(){ return $this->__f; }"
" public function setFlags($flags){ $this->__f = (int)$flags; }"
" public function asort($flags = 0){ asort($this->__d); return true; }"
" public function ksort($flags = 0){ ksort($this->__d); return true; }"
" public function uasort($callback){ uasort($this->__d, $callback); return true; }"
" public function uksort($callback){ uksort($this->__d, $callback); return true; }"
" public function natsort(){ uasort($this->__d, 'strnatcmp'); return true; }"
" public function natcasesort(){ uasort($this->__d, 'strnatcasecmp'); return true; }"
"}"
"class ArrayIterator implements SeekableIterator, ArrayAccess, Countable {"
" use __SplStoreT;"
" const STD_PROP_LIST = 1;"
" const ARRAY_AS_PROPS = 2;"
" public function __construct($array = [], $flags = 0){"
"  $this->__splInitStore($array, $flags, '__construct');"
"  reset($this->__d);"
" }"
" public function current(){"
"  if( key($this->__d) === null ){ return null; }"
"  return current($this->__d);"
" }"
" public function key(){ return key($this->__d); }"
" public function next(){ next($this->__d); }"
" public function rewind(){ reset($this->__d); }"
" public function valid(){ return key($this->__d) !== null; }"
" public function seek($offset){"
"  $offset = (int)$offset;"
"  if( $offset < 0 || $offset >= count($this->__d) ){"
"   throw new OutOfBoundsException('Seek position ' . $offset . ' is out of range');"
"  }"
"  reset($this->__d);"
"  for( $i = 0; $i < $offset; $i++ ){ next($this->__d); }"
" }"
"}"
"class ArrayObject implements IteratorAggregate, ArrayAccess, Countable {"
" use __SplStoreT;"
" const STD_PROP_LIST = 1;"
" const ARRAY_AS_PROPS = 2;"
" private $__it = 'ArrayIterator';"
" public function __construct($array = [], $flags = 0, $iteratorClass = 'ArrayIterator'){"
"  $this->__splInitStore($array, $flags, '__construct');"
"  if( $iteratorClass !== 'ArrayIterator' ){ $this->setIteratorClass($iteratorClass); }"
" }"
" public function getIterator(){"
"  $c = $this->__it;"
"  return new $c($this->__d);"
" }"
" public function exchangeArray($array){"
"  $old = $this->__d;"
"  $this->__splInitStore($array, $this->__f, 'exchangeArray');"
"  return $old;"
" }"
" public function setIteratorClass($iteratorClass){"
"  $c = (string)$iteratorClass;"
"  if( $c !== 'ArrayIterator'"
"   && (!class_exists($c) || !is_subclass_of($c, 'ArrayIterator')) ){"
"   throw new TypeError('ArrayObject::setIteratorClass(): Argument #1"
" ($iteratorClass) must be a class name derived from ArrayIterator, ' . $c . ' given');"
"  }"
"  $this->__it = $c;"
" }"
" public function getIteratorClass(){ return $this->__it; }"
" public function __get($name){"
"  if( $this->__f & 2 ){ return $this->__d[$name]; }"
"  return null;"
" }"
" public function __set($name, $value){"
"  if( $this->__f & 2 ){ $this->__d[$name] = $value; return; }"
"  $this->{$name} = $value;"
" }"
" public function __isset($name){"
"  if( $this->__f & 2 ){ return isset($this->__d[$name]); }"
"  return false;"
" }"
" public function __unset($name){"
"  if( $this->__f & 2 ){ unset($this->__d[$name]); }"
" }"
"}"
"function natsort(&$array){ return uasort($array, 'strnatcmp'); }"
"function natcasesort(&$array){ return uasort($array, 'strnatcasecmp'); }"
"interface OuterIterator extends Iterator {"
" public function getInnerIterator();"
"}"
"class IteratorIterator implements OuterIterator {"
" private $__in = null;"
" public function __construct($iterator, $class = null){"
"  while( $iterator instanceof IteratorAggregate ){ $iterator = $iterator->getIterator(); }"
"  if( !($iterator instanceof Iterator) ){"
"   throw new TypeError(get_class($this) . '::__construct(): Argument #1 ($iterator)"
" must be of type Traversable, ' . get_debug_type($iterator) . ' given');"
"  }"
"  $this->__in = $iterator;"
" }"
" public function getInnerIterator(){ return $this->__in; }"
" public function current(){ return $this->__in->current(); }"
" public function key(){ return $this->__in->key(); }"
" public function next(){ $this->__in->next(); }"
" public function rewind(){ $this->__in->rewind(); }"
" public function valid(){ return $this->__in->valid(); }"
"}"
"class LimitIterator extends IteratorIterator {"
" private $__off = 0;"
" private $__lim = -1;"
" private $__pos = 0;"
" public function __construct($iterator, $offset = 0, $limit = -1){"
"  $offset = (int)$offset; $limit = (int)$limit;"
"  if( $offset < 0 ){"
"   throw new ValueError('LimitIterator::__construct(): Argument #2 ($offset) must be"
" greater than or equal to 0');"
"  }"
"  if( $limit < -1 ){"
"   throw new ValueError('LimitIterator::__construct(): Argument #3 ($limit) must be"
" greater than or equal to -1');"
"  }"
"  parent::__construct($iterator);"
"  $this->__off = $offset;"
"  $this->__lim = $limit;"
" }"
" public function rewind(){"
"  $in = $this->getInnerIterator();"
"  $in->rewind();"
"  for( $i = 0; $i < $this->__off && $in->valid(); $i++ ){ $in->next(); }"
"  $this->__pos = $this->__off;"
" }"
" public function valid(){"
"  if( $this->__lim != -1 && $this->__pos >= $this->__off + $this->__lim ){ return false; }"
"  return $this->getInnerIterator()->valid();"
" }"
" public function next(){ $this->__pos++; $this->getInnerIterator()->next(); }"
" public function getPosition(){ return $this->__pos; }"
" public function seek($offset){"
"  $offset = (int)$offset;"
"  if( $offset < $this->__off ){"
"   throw new OutOfBoundsException('Cannot seek to ' . $offset . ' which is below the"
" offset ' . $this->__off);"
"  }"
"  if( $this->__lim != -1 && $offset >= $this->__off + $this->__lim ){"
"   throw new OutOfBoundsException('Cannot seek to ' . $offset . ' which is behind or"
" equal to the limit ' . $this->__lim . ' plus the offset ' . $this->__off);"
"  }"
"  $in = $this->getInnerIterator();"
"  $in->rewind();"
"  for( $i = 0; $i < $offset && $in->valid(); $i++ ){ $in->next(); }"
"  $this->__pos = $offset;"
"  return $this->__pos;"
" }"
"}"
"abstract class FilterIterator extends IteratorIterator {"
" abstract public function accept();"
" private function __fiFetch(){"
"  $in = $this->getInnerIterator();"
"  while( $in->valid() && !$this->accept() ){ $in->next(); }"
" }"
" public function rewind(){ $this->getInnerIterator()->rewind(); $this->__fiFetch(); }"
" public function next(){ $this->getInnerIterator()->next(); $this->__fiFetch(); }"
"}"
"class CallbackFilterIterator extends FilterIterator {"
" private $__cb = null;"
" public function __construct($iterator, $callback){"
"  parent::__construct($iterator);"
"  $this->__cb = $callback;"
" }"
" public function accept(){"
"  $in = $this->getInnerIterator();"
"  return (bool)call_user_func($this->__cb, $in->current(), $in->key(), $in);"
" }"
"}"
"class RegexIterator extends FilterIterator {"
" const USE_KEY = 1;"
" const INVERT_MATCH = 2;"
" const MATCH = 0;"
" const GET_MATCH = 1;"
" const ALL_MATCHES = 2;"
" const SPLIT = 3;"
" const REPLACE = 4;"
" public $replacement = null;"
" private $__re = '';"
" private $__mode = 0;"
" private $__rflags = 0;"
" private $__pflags = 0;"
" private $__cur = null;"
" public function __construct($iterator, $pattern, $mode = 0, $flags = 0, $pregFlags = 0){"
"  parent::__construct($iterator);"
"  $this->__re = (string)$pattern;"
"  $this->__mode = (int)$mode;"
"  $this->__rflags = (int)$flags;"
"  $this->__pflags = (int)$pregFlags;"
" }"
" public function accept(){"
"  $in = $this->getInnerIterator();"
"  if( !$in->valid() ){ return false; }"
"  $subject = ($this->__rflags & self::USE_KEY) ? $in->key() : $in->current();"
"  $subject = (string)$subject;"
"  $this->__cur = null;"
"  $ok = false;"
"  if( $this->__mode === self::MATCH ){"
"   $ok = preg_match($this->__re, $subject) > 0;"
"  }elseif( $this->__mode === self::GET_MATCH ){"
"   $m = null;"
"   $ok = preg_match($this->__re, $subject, $m, $this->__pflags) > 0;"
"   $this->__cur = $m;"
"  }elseif( $this->__mode === self::ALL_MATCHES ){"
"   $m = null;"
"   $ok = preg_match_all($this->__re, $subject, $m, $this->__pflags) > 0;"
"   $this->__cur = $m;"
"  }elseif( $this->__mode === self::SPLIT ){"
"   $this->__cur = preg_split($this->__re, $subject, -1, $this->__pflags);"
"   $ok = is_array($this->__cur) && count($this->__cur) > 1;"
"  }elseif( $this->__mode === self::REPLACE ){"
"   $n = 0;"
"   $this->__cur = preg_replace($this->__re, (string)$this->replacement, $subject, -1, $n);"
"   $ok = $n > 0;"
"  }"
"  if( $this->__rflags & self::INVERT_MATCH ){ $ok = !$ok; }"
"  return $ok;"
" }"
" public function current(){"
"  if( $this->__mode === self::MATCH ){ return $this->getInnerIterator()->current(); }"
"  return $this->__cur;"
" }"
" public function getRegex(){ return $this->__re; }"
" public function getMode(){ return $this->__mode; }"
" public function setMode($mode){ $this->__mode = (int)$mode; }"
" public function getFlags(){ return $this->__rflags; }"
" public function setFlags($flags){ $this->__rflags = (int)$flags; }"
" public function getPregFlags(){ return $this->__pflags; }"
" public function setPregFlags($pregFlags){ $this->__pflags = (int)$pregFlags; }"
"}"
"class AppendIterator implements OuterIterator {"
" private $__its = [];"
" private $__idx = 0;"
" public function __construct(){}"
" public function append($iterator){"
"  $this->__its[] = $iterator;"
"  if( count($this->__its) === 1 ){ $iterator->rewind(); }"
" }"
" public function getInnerIterator(){ return $this->__its[$this->__idx] ?? null; }"
" public function getIteratorIndex(){"
"  return isset($this->__its[$this->__idx]) ? $this->__idx : null;"
" }"
" public function getArrayIterator(){ return new ArrayIterator($this->__its); }"
" private function __apAdvance(){"
"  while( isset($this->__its[$this->__idx])"
"   && !$this->__its[$this->__idx]->valid()"
"   && isset($this->__its[$this->__idx + 1]) ){"
"   $this->__idx++;"
"   $this->__its[$this->__idx]->rewind();"
"  }"
" }"
" public function rewind(){"
"  $this->__idx = 0;"
"  if( isset($this->__its[0]) ){ $this->__its[0]->rewind(); }"
"  $this->__apAdvance();"
" }"
" public function valid(){"
"  $in = $this->getInnerIterator();"
"  return $in !== null && $in->valid();"
" }"
" public function current(){ $in = $this->getInnerIterator(); return $in ? $in->current() : null; }"
" public function key(){ $in = $this->getInnerIterator(); return $in ? $in->key() : null; }"
" public function next(){"
"  $in = $this->getInnerIterator();"
"  if( $in ){ $in->next(); }"
"  $this->__apAdvance();"
" }"
"}"
"class InfiniteIterator extends IteratorIterator {"
" public function next(){"
"  $in = $this->getInnerIterator();"
"  $in->next();"
"  if( !$in->valid() ){ $in->rewind(); }"
" }"
"}"
"class NoRewindIterator extends IteratorIterator {"
" public function rewind(){}"
"}"
"class WeakReference {"
" private $__h = 0;"
" private function __construct(){}"
" public static function create($object){"
"  if( !is_object($object) ){"
"   throw new TypeError('WeakReference::create(): Argument #1 ($object) must be"
" of type object, ' . get_debug_type($object) . ' given');"
"  }"
"  $w = new WeakReference();"
"  $w->__h = __weak_create($object);"
"  return $w;"
" }"
" public function get(){ return $this->__h ? __weak_get($this->__h) : null; }"
" public function __destruct(){"
"  if( $this->__h ){ __weak_drop($this->__h); $this->__h = 0; }"
" }"
"}"
"class WeakMap implements ArrayAccess, Countable, IteratorAggregate {"
" private $__e = [];"
" private function __wmPrune(){"
"  foreach( $this->__e as $id => $p ){"
"   if( __weak_get($p[0]) === null ){"
"    __weak_drop($p[0]);"
"    unset($this->__e[$id]);"
"   }"
"  }"
" }"
" public function offsetSet($object, $value){"
"  if( !is_object($object) ){"
"   throw new TypeError('WeakMap key must be an object');"
"  }"
"  $id = spl_object_id($object);"
"  if( isset($this->__e[$id]) && __weak_get($this->__e[$id][0]) !== null ){"
"   $this->__e[$id][1] = $value;"
"   return;"
"  }"
"  if( isset($this->__e[$id]) ){ __weak_drop($this->__e[$id][0]); }"
"  $this->__e[$id] = [__weak_create($object), $value];"
" }"
" public function offsetGet($object){"
"  if( !is_object($object) ){"
"   throw new TypeError('WeakMap key must be an object');"
"  }"
"  $id = spl_object_id($object);"
"  if( isset($this->__e[$id]) && __weak_get($this->__e[$id][0]) === $object ){"
"   return $this->__e[$id][1];"
"  }"
"  throw new Error('Object ' . get_class($object) . '#' . $id . ' not contained"
" in WeakMap');"
" }"
" public function offsetExists($object){"
"  if( !is_object($object) ){"
"   throw new TypeError('WeakMap key must be an object');"
"  }"
"  $id = spl_object_id($object);"
"  return isset($this->__e[$id]) && __weak_get($this->__e[$id][0]) === $object;"
" }"
" public function offsetUnset($object){"
"  if( !is_object($object) ){"
"   throw new TypeError('WeakMap key must be an object');"
"  }"
"  $id = spl_object_id($object);"
"  if( isset($this->__e[$id]) ){"
"   __weak_drop($this->__e[$id][0]);"
"   unset($this->__e[$id]);"
"  }"
" }"
" public function count(){"
"  $this->__wmPrune();"
"  return count($this->__e);"
" }"
" public function getIterator(): Generator {"
"  $this->__wmPrune();"
"  foreach( $this->__e as $p ){"
"   $o = __weak_get($p[0]);"
"   if( $o !== null ){ yield $o => $p[1]; }"
"  }"
" }"
" public function __destruct(){"
"  foreach( $this->__e as $p ){ __weak_drop($p[0]); }"
"  $this->__e = [];"
" }"
"}"
"class EmptyIterator implements Iterator {"
" public function current(){"
"  throw new BadMethodCallException('Accessing the value of an EmptyIterator');"
" }"
" public function key(){"
"  throw new BadMethodCallException('Accessing the key of an EmptyIterator');"
" }"
" public function next(){}"
" public function rewind(){}"
" public function valid(){ return false; }"
"}"
"class SplDoublyLinkedList implements Iterator, Countable, ArrayAccess {"
" const IT_MODE_LIFO = 2;"
" const IT_MODE_FIFO = 0;"
" const IT_MODE_DELETE = 1;"
" const IT_MODE_KEEP = 0;"
" private $__q = [];"
" private $__mode = 0;"
" private $__i = 0;"
" public function __construct(){"
"  if( $this instanceof SplStack ){ $this->__mode = 2; }"
" }"
" public function setIteratorMode($mode){"
"  $mode = (int)$mode;"
"  if( ($this instanceof SplStack || $this instanceof SplQueue)"
"   && ($mode & 2) !== ($this->__mode & 2) ){"
"   throw new RuntimeException(\"Iterators' LIFO/FIFO modes for SplStack/SplQueue"
" objects are frozen\");"
"  }"
"  $this->__mode = $mode;"
" }"
" public function getIteratorMode(){ return $this->__mode; }"
" public function push($value){ $this->__q[] = $value; }"
" public function pop(){"
"  if( count($this->__q) === 0 ){"
"   throw new RuntimeException(\"Can't pop from an empty datastructure\");"
"  }"
"  return array_pop($this->__q);"
" }"
" public function shift(){"
"  if( count($this->__q) === 0 ){"
"   throw new RuntimeException(\"Can't shift from an empty datastructure\");"
"  }"
"  return array_shift($this->__q);"
" }"
" public function unshift($value){ array_unshift($this->__q, $value); }"
" public function top(){"
"  if( count($this->__q) === 0 ){"
"   throw new RuntimeException(\"Can't peek at an empty datastructure\");"
"  }"
"  return $this->__q[count($this->__q) - 1];"
" }"
" public function bottom(){"
"  if( count($this->__q) === 0 ){"
"   throw new RuntimeException(\"Can't peek at an empty datastructure\");"
"  }"
"  return $this->__q[0];"
" }"
" public function isEmpty(){ return count($this->__q) === 0; }"
" public function count(){ return count($this->__q); }"
" public function toArray(){ return $this->__q; }"
" public function add($index, $value){"
"  $index = (int)$index;"
"  if( $index < 0 || $index > count($this->__q) ){"
"   throw new OutOfRangeException(get_class($this) === 'SplDoublyLinkedList'"
"    ? 'SplDoublyLinkedList::add(): Argument #1 ($index) is out of range'"
"    : get_class($this) . '::add(): Argument #1 ($index) is out of range');"
"  }"
"  array_splice($this->__q, $index, 0, [$value]);"
" }"
" public function offsetExists($index){"
"  return is_int($index) || ctype_digit((string)$index)"
"   ? ((int)$index >= 0 && (int)$index < count($this->__q)) : false;"
" }"
" public function offsetGet($index){"
"  $index = (int)$index;"
"  if( $index < 0 || $index >= count($this->__q) ){"
"   throw new OutOfRangeException('SplDoublyLinkedList::offsetGet(): Argument #1"
" ($index) is out of range');"
"  }"
"  return $this->__q[$index];"
" }"
" public function offsetSet($index, $value){"
"  if( $index === null ){ $this->__q[] = $value; return; }"
"  $index = (int)$index;"
"  if( $index < 0 || $index >= count($this->__q) ){"
"   throw new OutOfRangeException('SplDoublyLinkedList::offsetSet(): Argument #1"
" ($index) is out of range');"
"  }"
"  $this->__q[$index] = $value;"
" }"
" public function offsetUnset($index){"
"  $index = (int)$index;"
"  if( $index < 0 || $index >= count($this->__q) ){"
"   throw new OutOfRangeException('SplDoublyLinkedList::offsetUnset(): Argument #1"
" ($index) is out of range');"
"  }"
"  array_splice($this->__q, $index, 1);"
" }"
" public function rewind(){"
"  $this->__i = ($this->__mode & 2) ? count($this->__q) - 1 : 0;"
" }"
" public function valid(){"
"  return $this->__i >= 0 && $this->__i < count($this->__q);"
" }"
" public function current(){ return $this->__q[$this->__i] ?? null; }"
" public function key(){ return $this->__i; }"
" public function next(){"
"  if( $this->__mode & 1 ){"
"   /* IT_MODE_DELETE consumes the element just visited */"
"   if( $this->__mode & 2 ){ array_pop($this->__q); $this->__i = count($this->__q) - 1; }"
"   else { array_shift($this->__q); }"
"  }else{"
"   $this->__i += ($this->__mode & 2) ? -1 : 1;"
"  }"
" }"
" public function prev(){ $this->__i += ($this->__mode & 2) ? 1 : -1; }"
"}"
"class SplStack extends SplDoublyLinkedList {}"
"class SplQueue extends SplDoublyLinkedList {"
" public function enqueue($value){ $this->push($value); }"
" public function dequeue(){ return $this->shift(); }"
"}"
"abstract class SplHeap implements Iterator, Countable {"
" private $__h = [];"
" abstract protected function compare($value1, $value2);"
" private function __hSiftUp($i){"
"  while( $i > 0 ){"
"   $p = ($i - 1) >> 1;"
"   if( $this->compare($this->__h[$i], $this->__h[$p]) <= 0 ){ break; }"
"   $t = $this->__h[$p]; $this->__h[$p] = $this->__h[$i]; $this->__h[$i] = $t;"
"   $i = $p;"
"  }"
" }"
" private function __hSiftDown($i){"
"  $n = count($this->__h);"
"  for(;;){"
"   $l = 2 * $i + 1; $r = $l + 1; $b = $i;"
"   if( $l < $n && $this->compare($this->__h[$l], $this->__h[$b]) > 0 ){ $b = $l; }"
"   if( $r < $n && $this->compare($this->__h[$r], $this->__h[$b]) > 0 ){ $b = $r; }"
"   if( $b === $i ){ break; }"
"   $t = $this->__h[$b]; $this->__h[$b] = $this->__h[$i]; $this->__h[$i] = $t;"
"   $i = $b;"
"  }"
" }"
" public function insert($value){"
"  $this->__h[] = $value;"
"  $this->__hSiftUp(count($this->__h) - 1);"
"  return true;"
" }"
" public function extract(){"
"  $n = count($this->__h);"
"  if( $n === 0 ){"
"   throw new RuntimeException(\"Can't extract from an empty heap\");"
"  }"
"  $top = $this->__h[0];"
"  $last = array_pop($this->__h);"
"  if( $n > 1 ){"
"   $this->__h[0] = $last;"
"   $this->__hSiftDown(0);"
"  }"
"  return $top;"
" }"
" public function top(){"
"  if( count($this->__h) === 0 ){"
"   throw new RuntimeException(\"Can't peek at an empty heap\");"
"  }"
"  return $this->__h[0];"
" }"
" public function isEmpty(){ return count($this->__h) === 0; }"
" public function count(){ return count($this->__h); }"
" public function isCorrupted(){ return false; }"
" public function recoverFromCorruption(){ return true; }"
" public function rewind(){}"
" public function valid(){ return count($this->__h) > 0; }"
" public function current(){ return count($this->__h) ? $this->__h[0] : null; }"
" public function key(){ return count($this->__h) - 1; }"
" public function next(){ if( count($this->__h) ){ $this->extract(); } }"
"}"
"class SplMinHeap extends SplHeap {"
" protected function compare($value1, $value2){ return $value2 <=> $value1; }"
"}"
"class SplMaxHeap extends SplHeap {"
" protected function compare($value1, $value2){ return $value1 <=> $value2; }"
"}"
"class SplPriorityQueue implements Iterator, Countable {"
" const EXTR_DATA = 1;"
" const EXTR_PRIORITY = 2;"
" const EXTR_BOTH = 3;"
" private $__h = [];"
" private $__serial = PHP_INT_MAX;"
" private $__flags = 1;"
" public function compare($priority1, $priority2){ return $priority1 <=> $priority2; }"
" private function __pqCmp($a, $b){"
"  /* NO tie-break: php's heap swaps only on strictly-greater, which fixes"
"   * the (documented-as-undefined) equal-priority order it exhibits */"
"  return $this->compare($a[0], $b[0]);"
" }"
" private function __pqSiftUp($i){"
"  while( $i > 0 ){"
"   $p = ($i - 1) >> 1;"
"   if( $this->__pqCmp($this->__h[$i], $this->__h[$p]) <= 0 ){ break; }"
"   $t = $this->__h[$p]; $this->__h[$p] = $this->__h[$i]; $this->__h[$i] = $t;"
"   $i = $p;"
"  }"
" }"
" private function __pqSiftDown($i){"
"  $n = count($this->__h);"
"  for(;;){"
"   $l = 2 * $i + 1; $r = $l + 1; $b = $i;"
"   if( $l < $n && $this->__pqCmp($this->__h[$l], $this->__h[$b]) > 0 ){ $b = $l; }"
"   if( $r < $n && $this->__pqCmp($this->__h[$r], $this->__h[$b]) > 0 ){ $b = $r; }"
"   if( $b === $i ){ break; }"
"   $t = $this->__h[$b]; $this->__h[$b] = $this->__h[$i]; $this->__h[$i] = $t;"
"   $i = $b;"
"  }"
" }"
" public function insert($value, $priority){"
"  $this->__h[] = [$priority, $this->__serial--, $value];"
"  $this->__pqSiftUp(count($this->__h) - 1);"
"  return true;"
" }"
" private function __pqShape($node){"
"  if( $this->__flags === self::EXTR_BOTH ){"
"   return ['data' => $node[2], 'priority' => $node[0]];"
"  }"
"  if( $this->__flags === self::EXTR_PRIORITY ){ return $node[0]; }"
"  return $node[2];"
" }"
" public function extract(){"
"  $n = count($this->__h);"
"  if( $n === 0 ){"
"   throw new RuntimeException(\"Can't extract from an empty heap\");"
"  }"
"  $top = $this->__h[0];"
"  $last = array_pop($this->__h);"
"  if( $n > 1 ){"
"   $this->__h[0] = $last;"
"   $this->__pqSiftDown(0);"
"  }"
"  return $this->__pqShape($top);"
" }"
" public function top(){"
"  if( count($this->__h) === 0 ){"
"   throw new RuntimeException(\"Can't peek at an empty heap\");"
"  }"
"  return $this->__pqShape($this->__h[0]);"
" }"
" public function setExtractFlags($flags){ $this->__flags = (int)$flags; }"
" public function getExtractFlags(){ return $this->__flags; }"
" public function isEmpty(){ return count($this->__h) === 0; }"
" public function count(){ return count($this->__h); }"
" public function isCorrupted(){ return false; }"
" public function recoverFromCorruption(){ return true; }"
" public function rewind(){}"
" public function valid(){ return count($this->__h) > 0; }"
" public function current(){ return count($this->__h) ? $this->__pqShape($this->__h[0]) : null; }"
" public function key(){ return count($this->__h) - 1; }"
" public function next(){ if( count($this->__h) ){ $this->extract(); } }"
"}"
"class SplFixedArray implements ArrayAccess, Countable, IteratorAggregate, JsonSerializable {"
" private $__a = [];"
" private $__n = 0;"
" public function __construct($size = 0){"
"  $this->setSize((int)$size);"
" }"
" private function __faIdx($index, $method){"
"  if( !is_int($index) ){"
"   if( is_string($index) && ctype_digit($index) ){"
"    $index = (int)$index;"
"   }else{"
"    throw new TypeError('Cannot access offset of type ' . get_debug_type($index)"
"     . ' on SplFixedArray');"
"   }"
"  }"
"  if( $index < 0 || $index >= $this->__n ){"
"   throw new OutOfBoundsException('Index invalid or out of range');"
"  }"
"  return $index;"
" }"
" public function offsetExists($index){"
"  if( !is_int($index) && !(is_string($index) && ctype_digit($index)) ){ return false; }"
"  $index = (int)$index;"
"  return $index >= 0 && $index < $this->__n && $this->__a[$index] !== null;"
" }"
" public function offsetGet($index){ return $this->__a[$this->__faIdx($index, 'offsetGet')]; }"
" public function offsetSet($index, $value){ $this->__a[$this->__faIdx($index, 'offsetSet')] = $value; }"
" public function offsetUnset($index){ $this->__a[$this->__faIdx($index, 'offsetUnset')] = null; }"
" public function getSize(){ return $this->__n; }"
" public function setSize($size){"
"  $size = (int)$size;"
"  if( $size < 0 ){"
"   throw new ValueError('SplFixedArray::setSize(): Argument #1 ($size) must be"
" greater than or equal to 0');"
"  }"
"  if( $size < $this->__n ){"
"   $this->__a = array_slice($this->__a, 0, $size);"
"  }else{"
"   for( $i = $this->__n; $i < $size; $i++ ){ $this->__a[$i] = null; }"
"  }"
"  $this->__n = $size;"
"  return true;"
" }"
" public function count(){ return $this->__n; }"
" public function toArray(){ return $this->__a; }"
" public static function fromArray($array, $preserveKeys = true){"
"  $f = new SplFixedArray(0);"
"  if( $preserveKeys ){"
"   $max = -1;"
"   foreach( $array as $k => $v ){"
"    if( !is_int($k) || $k < 0 ){"
"     throw new InvalidArgumentException('array must contain only positive integer keys');"
"    }"
"    if( $k > $max ){ $max = $k; }"
"   }"
"   $f->setSize($max + 1);"
"   foreach( $array as $k => $v ){ $f[$k] = $v; }"
"  }else{"
"   $vals = array_values($array);"
"   $f->setSize(count($vals));"
"   foreach( $vals as $k => $v ){ $f[$k] = $v; }"
"  }"
"  return $f;"
" }"
" public function getIterator(): Generator {"
"  for( $i = 0; $i < $this->__n; $i++ ){ yield $i => $this->__a[$i]; }"
" }"
" public function jsonSerialize(){ return $this->__a; }"
"}"
"class SplObjectStorage implements Countable, Iterator, ArrayAccess {"
" private $__o = [];"
" private $__i = 0;"
" public function attach($object, $info = null){"
"  __spl_deprecated('Method SplObjectStorage::attach() is deprecated since 8.5, use"
" method SplObjectStorage::offsetSet() instead');"
"  $this->offsetSet($object, $info);"
" }"
" public function detach($object){"
"  __spl_deprecated('Method SplObjectStorage::detach() is deprecated since 8.5, use"
" method SplObjectStorage::offsetUnset() instead');"
"  $this->offsetUnset($object);"
" }"
" public function contains($object){"
"  __spl_deprecated('Method SplObjectStorage::contains() is deprecated since 8.5, use"
" method SplObjectStorage::offsetExists() instead');"
"  return $this->offsetExists($object);"
" }"
" public function offsetSet($object, $info = null){"
"  $this->__o[spl_object_id($object)] = [$object, $info];"
" }"
" public function offsetExists($object){"
"  return isset($this->__o[spl_object_id($object)]);"
" }"
" public function offsetGet($object){"
"  $id = spl_object_id($object);"
"  if( !isset($this->__o[$id]) ){"
"   throw new UnexpectedValueException('Object not found');"
"  }"
"  return $this->__o[$id][1];"
" }"
" public function offsetUnset($object){"
"  unset($this->__o[spl_object_id($object)]);"
" }"
" public function addAll($storage){"
"  foreach( $storage as $obj ){"
"   $this->offsetSet($obj, $storage[$obj]);"
"  }"
"  return $this->count();"
" }"
" public function removeAll($storage){"
"  foreach( $storage as $obj ){ $this->offsetUnset($obj); }"
"  return $this->count();"
" }"
" public function removeAllExcept($storage){"
"  foreach( $this->__o as $id => $pair ){"
"   if( !$storage->offsetExists($pair[0]) ){ unset($this->__o[$id]); }"
"  }"
"  return $this->count();"
" }"
" public function getHash($object){ return spl_object_hash($object); }"
" public function count($mode = 0){ return count($this->__o); }"
" public function getInfo(){"
"  $pair = array_values($this->__o)[$this->__i] ?? null;"
"  return $pair === null ? null : $pair[1];"
" }"
" public function setInfo($info){"
"  $keys = array_keys($this->__o);"
"  if( isset($keys[$this->__i]) ){ $this->__o[$keys[$this->__i]][1] = $info; }"
" }"
" public function rewind(){ $this->__i = 0; }"
" public function valid(){ return $this->__i < count($this->__o); }"
" public function key(){ return $this->__i; }"
" public function current(){"
"  $pair = array_values($this->__o)[$this->__i] ?? null;"
"  return $pair === null ? null : $pair[0];"
" }"
" public function next(){ $this->__i++; }"
"}"
"interface SplObserver {"
" public function update(SplSubject $subject);"
"}"
"interface SplSubject {"
" public function attach(SplObserver $observer);"
" public function detach(SplObserver $observer);"
" public function notify();"
"}"
;

PH7_PRIVATE sxi32 PH7_VmInstallSpl(ph7_vm *pVm)
{
	ph7_create_function(&(*pVm),"__spl_deprecated",vm_builtin_spl_deprecated,0);
	ph7_create_function(&(*pVm),"__weak_create",vm_builtin_weak_create,0);
	ph7_create_function(&(*pVm),"__weak_get",vm_builtin_weak_get,0);
	ph7_create_function(&(*pVm),"__weak_drop",vm_builtin_weak_drop,0);
	return PH7_VmEvalBuiltinChunk(&(*pVm),zSplLib,sizeof(zSplLib)-1);
}

#endif /* PH7_DISABLE_BUILTIN_FUNC */

#ifdef PH7_DISABLE_BUILTIN_FUNC
/* Tiny build: no SPL (builtin layer disabled) */
PH7_PRIVATE sxi32 PH7_VmInstallSpl(ph7_vm *pVm){ (void)pVm; return SXRET_OK; }
#endif
