@echo off
:: SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
:: SPDX-License-Identifier: BSD-3-Clause
setlocal enabledelayedexpansion

:: Script to generate NMake rules for source files

set SRC_DIR=%~1
set OUTFILE=%~2
set BUILD_DIR=$^(BUILD_DIR^)
set FULL_DIR=$^(BUILD_DIR^)/full
set COVERAGE_DIR=$^(BUILD_DIR^)/coverage

> "%OUTFILE%" echo # Pattern rules generated by `build-aux/patterns.bat %SRC_DIR% %OUTFILE%`
>> "%OUTFILE%" echo # DO NOT EDIT THIS FILE DIRECTLY
>> "%OUTFILE%" echo.

>> "%OUTFILE%" echo !BUILD_DIR!:
>> "%OUTFILE%" echo     @if not exist "!BUILD_DIR!" mkdir "!BUILD_DIR!"
>> "%OUTFILE%" echo !FULL_DIR!:
>> "%OUTFILE%" echo     @if not exist "!FULL_DIR!" mkdir "!FULL_DIR!"
>> "%OUTFILE%" echo !FULL_DIR!/!SRC_DIR!:
>> "%OUTFILE%" echo     @if not exist "!FULL_DIR!/!SRC_DIR!" mkdir "!FULL_DIR!/!SRC_DIR!"
>> "%OUTFILE%" echo !COVERAGE_DIR!:
>> "%OUTFILE%" echo     @if not exist "!COVERAGE_DIR!" mkdir "!COVERAGE_DIR!"
>> "%OUTFILE%" echo !COVERAGE_DIR!/!SRC_DIR!:
>> "%OUTFILE%" echo     @if not exist "!COVERAGE_DIR!/!SRC_DIR!" mkdir "!COVERAGE_DIR!/!SRC_DIR!"

for /f "delims=" %%D in ('dir /s /b /ad "%SRC_DIR%"') do (
    set SRC=%%D
    set SRC_SUB=!SRC:%CD%\=!
    set SRC_SUB=!SRC_SUB:\=/!

    >> "%OUTFILE%" echo {!SRC_SUB!}.c{!FULL_DIR!/!SRC_SUB!}.obj:
    >> "%OUTFILE%" echo     @if not exist "!FULL_DIR!/!SRC_SUB!" mkdir "!FULL_DIR!/!SRC_SUB!"
    >> "%OUTFILE%" echo     $^(CC^) $^(CFLAGS^) /Fo"$@" /c $^<
    >> "%OUTFILE%" echo {!SRC_SUB!}.c{!COVERAGE_DIR!/!SRC_SUB!}.obj:
    >> "%OUTFILE%" echo     @if not exist "!COVERAGE_DIR!/!SRC_SUB!" mkdir "!COVERAGE_DIR!/!SRC_SUB!"
    >> "%OUTFILE%" echo     $^(CC^) $^(COVERAGE_CFLAGS^) /Fo"$@" /c $^<
)
