# Pattern rules generated by `build-aux/patterns.bat full tiny coverage`
# DO NOT EDIT THIS FILE DIRECTLY

$(BUILD_DIR):
    @if not exist "$(BUILD_DIR)" mkdir "$(BUILD_DIR)"

$(BUILD_DIR)/full:
    @if not exist "$(BUILD_DIR)/full" mkdir "$(BUILD_DIR)/full"
$(BUILD_DIR)/full/src:
    @if not exist "$(BUILD_DIR)/full/src" mkdir "$(BUILD_DIR)/full/src"
$(BUILD_DIR)/full/phl$(BIN_SUFFIX): $(OBJECTS:/src/=/full/src/)
    @if not exist "$(BUILD_DIR)/full" mkdir "$(BUILD_DIR)/full"
    $(CC) $(full_CFLAGS) /Fe$@ $** $(full_LDFLAGS)

{src/ph7}.c{$(BUILD_DIR)/full/src/ph7}.obj:
    @if not exist "$(BUILD_DIR)/full/src/ph7" mkdir "$(BUILD_DIR)/full/src/ph7"
    $(CC) $(full_CFLAGS) /Fo"$@" /c $<
{src/phl}.c{$(BUILD_DIR)/full/src/phl}.obj:
    @if not exist "$(BUILD_DIR)/full/src/phl" mkdir "$(BUILD_DIR)/full/src/phl"
    $(CC) $(full_CFLAGS) /Fo"$@" /c $<
{src/sx}.c{$(BUILD_DIR)/full/src/sx}.obj:
    @if not exist "$(BUILD_DIR)/full/src/sx" mkdir "$(BUILD_DIR)/full/src/sx"
    $(CC) $(full_CFLAGS) /Fo"$@" /c $<

$(BUILD_DIR)/tiny:
    @if not exist "$(BUILD_DIR)/tiny" mkdir "$(BUILD_DIR)/tiny"
$(BUILD_DIR)/tiny/src:
    @if not exist "$(BUILD_DIR)/tiny/src" mkdir "$(BUILD_DIR)/tiny/src"
$(BUILD_DIR)/tiny/phl$(BIN_SUFFIX): $(OBJECTS:/src/=/tiny/src/)
    @if not exist "$(BUILD_DIR)/tiny" mkdir "$(BUILD_DIR)/tiny"
    $(CC) $(tiny_CFLAGS) /Fe$@ $** $(tiny_LDFLAGS)

{src/ph7}.c{$(BUILD_DIR)/tiny/src/ph7}.obj:
    @if not exist "$(BUILD_DIR)/tiny/src/ph7" mkdir "$(BUILD_DIR)/tiny/src/ph7"
    $(CC) $(tiny_CFLAGS) /Fo"$@" /c $<
{src/phl}.c{$(BUILD_DIR)/tiny/src/phl}.obj:
    @if not exist "$(BUILD_DIR)/tiny/src/phl" mkdir "$(BUILD_DIR)/tiny/src/phl"
    $(CC) $(tiny_CFLAGS) /Fo"$@" /c $<
{src/sx}.c{$(BUILD_DIR)/tiny/src/sx}.obj:
    @if not exist "$(BUILD_DIR)/tiny/src/sx" mkdir "$(BUILD_DIR)/tiny/src/sx"
    $(CC) $(tiny_CFLAGS) /Fo"$@" /c $<

$(BUILD_DIR)/coverage:
    @if not exist "$(BUILD_DIR)/coverage" mkdir "$(BUILD_DIR)/coverage"
$(BUILD_DIR)/coverage/src:
    @if not exist "$(BUILD_DIR)/coverage/src" mkdir "$(BUILD_DIR)/coverage/src"
$(BUILD_DIR)/coverage/phl$(BIN_SUFFIX): $(OBJECTS:/src/=/coverage/src/)
    @if not exist "$(BUILD_DIR)/coverage" mkdir "$(BUILD_DIR)/coverage"
    $(CC) $(coverage_CFLAGS) /Fe$@ $** $(coverage_LDFLAGS)

{src/ph7}.c{$(BUILD_DIR)/coverage/src/ph7}.obj:
    @if not exist "$(BUILD_DIR)/coverage/src/ph7" mkdir "$(BUILD_DIR)/coverage/src/ph7"
    $(CC) $(coverage_CFLAGS) /Fo"$@" /c $<
{src/phl}.c{$(BUILD_DIR)/coverage/src/phl}.obj:
    @if not exist "$(BUILD_DIR)/coverage/src/phl" mkdir "$(BUILD_DIR)/coverage/src/phl"
    $(CC) $(coverage_CFLAGS) /Fo"$@" /c $<
{src/sx}.c{$(BUILD_DIR)/coverage/src/sx}.obj:
    @if not exist "$(BUILD_DIR)/coverage/src/sx" mkdir "$(BUILD_DIR)/coverage/src/sx"
    $(CC) $(coverage_CFLAGS) /Fo"$@" /c $<

