# Pattern rules generated by `build-aux/patterns.bat src build-aux/patterns.mk`
# DO NOT EDIT THIS FILE DIRECTLY

$(BUILD_DIR):
    @if not exist "$(BUILD_DIR)" mkdir "$(BUILD_DIR)"
$(BUILD_DIR)/src:
    @if not exist "$(BUILD_DIR)/src" mkdir "$(BUILD_DIR)/src"
$(BUILD_DIR)/coverage:
    @if not exist "$(BUILD_DIR)/coverage" mkdir "$(BUILD_DIR)/coverage"
$(BUILD_DIR)/coverage/src:
    @if not exist "$(BUILD_DIR)/coverage/src" mkdir "$(BUILD_DIR)/coverage/src"
{src/ph7}.c{$(BUILD_DIR)/src/ph7}.obj:
    @if not exist "$(BUILD_DIR)/src/ph7" mkdir "$(BUILD_DIR)/src/ph7"
    $(CC) $(CFLAGS) /Fo"$@" /c $<
{src/ph7}.c{$(BUILD_DIR)/coverage/src/ph7}.obj:
    @if not exist "$(BUILD_DIR)/coverage/src/ph7" mkdir "$(BUILD_DIR)/coverage/src/ph7"
    $(CC) $(COVERAGE_CFLAGS) /Fo"$@" /c $<
{src/phl}.c{$(BUILD_DIR)/src/phl}.obj:
    @if not exist "$(BUILD_DIR)/src/phl" mkdir "$(BUILD_DIR)/src/phl"
    $(CC) $(CFLAGS) /Fo"$@" /c $<
{src/phl}.c{$(BUILD_DIR)/coverage/src/phl}.obj:
    @if not exist "$(BUILD_DIR)/coverage/src/phl" mkdir "$(BUILD_DIR)/coverage/src/phl"
    $(CC) $(COVERAGE_CFLAGS) /Fo"$@" /c $<
