@echo off
:: SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
:: SPDX-License-Identifier: BSD-3-Clause
setlocal enabledelayedexpansion

:: Script to generate NMake rules for source files
:: Usage: patterns.bat full tiny coverage

set MODES=%*
set SRC_DIR=src
set OUTFILE=build-aux/patterns.mk
set BUILD_DIR=$^(BUILD_DIR^)

> "%OUTFILE%" echo # Pattern rules generated by `build-aux/patterns.bat %MODES%`
>> "%OUTFILE%" echo # DO NOT EDIT THIS FILE DIRECTLY
>> "%OUTFILE%" echo.

>> "%OUTFILE%" echo !BUILD_DIR!:
>> "%OUTFILE%" echo     @if not exist "!BUILD_DIR!" mkdir "!BUILD_DIR!"
>> "%OUTFILE%" echo.

for %%X in (%MODES%) do (
    set DIR_VAR=%%X
    set DIR_VALUE=$^(BUILD_DIR^)/%%X
    
    >> "%OUTFILE%" echo !DIR_VALUE!:
    >> "%OUTFILE%" echo     @if not exist "!DIR_VALUE!" mkdir "!DIR_VALUE!"
    >> "%OUTFILE%" echo !DIR_VALUE!/!SRC_DIR!:
    >> "%OUTFILE%" echo     @if not exist "!DIR_VALUE!/!SRC_DIR!" mkdir "!DIR_VALUE!/!SRC_DIR!"

    >> "%OUTFILE%" echo !DIR_VALUE!/phl$^(BIN_SUFFIX^): $^(OBJECTS:/src/=/%%X/src/^)
    >> "%OUTFILE%" echo     @if not exist "!DIR_VALUE!" mkdir "!DIR_VALUE!"
    >> "%OUTFILE%" echo     $^(CC^) $^(%%X_CFLAGS^) /Fe$@ $^** $^(%%X_LDFLAGS^)
    >> "%OUTFILE%" echo.

    for /f "delims=" %%D in ('dir /s /b /ad "%SRC_DIR%"') do (
        set SRC=%%D
        set SRC_SUB=!SRC:%CD%\=!
        set SRC_SUB=!SRC_SUB:\=/!

        >> "%OUTFILE%" echo {!SRC_SUB!}.c{!DIR_VALUE!/!SRC_SUB!}.obj:
        >> "%OUTFILE%" echo     @if not exist "!DIR_VALUE!/!SRC_SUB!" mkdir "!DIR_VALUE!/!SRC_SUB!"
        >> "%OUTFILE%" echo     $^(CC^) $^(!DIR_VAR!_CFLAGS^) /Fo"$@" /c $^<
    )

    >> "%OUTFILE%" echo.
)
