# Pattern rules generated by `build-aux/patterns.bat full coverage`
# DO NOT EDIT THIS FILE DIRECTLY

$(BUILD_DIR):
    @if not exist "$(BUILD_DIR)" mkdir "$(BUILD_DIR)"

$(BUILD_DIR)/full:
    @if not exist "$(BUILD_DIR)/full" mkdir "$(BUILD_DIR)/full"
$(BUILD_DIR)/full/src:
    @if not exist "$(BUILD_DIR)/full/src" mkdir "$(BUILD_DIR)/full/src"
{src/ph7}.c{$(BUILD_DIR)/full/src/ph7}.obj:
    @if not exist "$(BUILD_DIR)/full/src/ph7" mkdir "$(BUILD_DIR)/full/src/ph7"
    $(CC) $(full_CFLAGS) /Fo"$@" /c $<
{src/phl}.c{$(BUILD_DIR)/full/src/phl}.obj:
    @if not exist "$(BUILD_DIR)/full/src/phl" mkdir "$(BUILD_DIR)/full/src/phl"
    $(CC) $(full_CFLAGS) /Fo"$@" /c $<
{src/sx}.c{$(BUILD_DIR)/full/src/sx}.obj:
    @if not exist "$(BUILD_DIR)/full/src/sx" mkdir "$(BUILD_DIR)/full/src/sx"
    $(CC) $(full_CFLAGS) /Fo"$@" /c $<

$(BUILD_DIR)/coverage:
    @if not exist "$(BUILD_DIR)/coverage" mkdir "$(BUILD_DIR)/coverage"
$(BUILD_DIR)/coverage/src:
    @if not exist "$(BUILD_DIR)/coverage/src" mkdir "$(BUILD_DIR)/coverage/src"
{src/ph7}.c{$(BUILD_DIR)/coverage/src/ph7}.obj:
    @if not exist "$(BUILD_DIR)/coverage/src/ph7" mkdir "$(BUILD_DIR)/coverage/src/ph7"
    $(CC) $(coverage_CFLAGS) /Fo"$@" /c $<
{src/phl}.c{$(BUILD_DIR)/coverage/src/phl}.obj:
    @if not exist "$(BUILD_DIR)/coverage/src/phl" mkdir "$(BUILD_DIR)/coverage/src/phl"
    $(CC) $(coverage_CFLAGS) /Fo"$@" /c $<
{src/sx}.c{$(BUILD_DIR)/coverage/src/sx}.obj:
    @if not exist "$(BUILD_DIR)/coverage/src/sx" mkdir "$(BUILD_DIR)/coverage/src/sx"
    $(CC) $(coverage_CFLAGS) /Fo"$@" /c $<

