--CREDITS--
SPDX-FileCopyrightText: 2026 Alexandre Gomes Gaigalas <alganet@gmail.com>
SPDX-License-Identifier: BSD-3-Clause
--TEST--
argon2i/argon2id: hash shape, verify (fixed vectors + roundtrip), get_info, needs_rehash, algos
--DESCRIPTION--
PASSWORD_ARGON2I and PASSWORD_ARGON2ID were undefined constants and
password_algos() an undefined function, so php's recommended memory-hard
password hash could not be spelled. The fixed hashes below were generated by
php 8.5 and must verify byte-exactly (the tag depends on every parameter, the
salt, the version and the lane count — the p=2 and p=4 vectors exercise the
multi-lane fill); the roundtrip half proves fresh hashes carry php's exact
string shape. get_info parses parameters leniently (defaults for a string
that does not parse), needs_rehash compares m/t/p against the requested
options, and password_algos() answers php's list in php's order.
--FILE--
<?php
$vectors = [
    '$argon2i$v=19$m=32,t=1,p=1$UXExTm9kaFlKS0JFY3N6Tw$Z3rb+NYIBNA80CWZDmmy/DpY50MmbqhLeXyP4ITecS4',
    '$argon2i$v=19$m=64,t=3,p=2$ZjIuVmM0di80UlhpR1Vnag$43xhsNpqY4Q9k8ZH8mcBUEfx1ueGnrSDfSJK2Em5lQo',
    '$argon2id$v=19$m=32,t=1,p=1$ODFjcm5LNDlLWDVrNFJVQg$jiEDocsjtWS17lexS0wMnCbiNJxqajY9b9gXOhsJR0Q',
    '$argon2id$v=19$m=256,t=2,p=4$R0g3ZHRWSmFrckRBN0RKaw$TiXaSiQrK3gqhwSJQwgRelZOA+AyP3BNF9vcsLDPa0o',
];
foreach ($vectors as $h) {
    var_dump(password_verify('secret', $h));
    var_dump(password_verify('wrong', $h));
}
$h = password_hash('roundtrip', PASSWORD_ARGON2ID, ['memory_cost' => 32, 'time_cost' => 1, 'threads' => 1]);
var_dump((bool)preg_match('~^\$argon2id\$v=19\$m=32,t=1,p=1\$[A-Za-z0-9+/]{22}\$[A-Za-z0-9+/]{43}$~', $h));
var_dump(password_verify('roundtrip', $h));
$hi = password_hash("nul\0led", PASSWORD_ARGON2I, ['memory_cost' => 32, 'time_cost' => 1, 'threads' => 1]);
var_dump(password_verify("nul\0led", $hi), password_verify("nul", $hi));
var_dump(password_get_info($vectors[1]));
var_dump(password_get_info('$argon2id$garbage'));
var_dump(password_needs_rehash($vectors[2], PASSWORD_ARGON2ID, ['memory_cost' => 32, 'time_cost' => 1, 'threads' => 1]));
var_dump(password_needs_rehash($vectors[2], PASSWORD_ARGON2ID));
var_dump(password_needs_rehash($vectors[2], PASSWORD_ARGON2I, ['memory_cost' => 32, 'time_cost' => 1, 'threads' => 1]));
var_dump(password_needs_rehash($vectors[2], PASSWORD_BCRYPT));
var_dump(password_needs_rehash(password_hash('x', 2, ['memory_cost' => 32, 'time_cost' => 1]), 'argon2i', ['memory_cost' => 32, 'time_cost' => 1]));
var_dump(password_algos());
echo PASSWORD_ARGON2I, ' ', PASSWORD_ARGON2ID, ' ',
    PASSWORD_ARGON2_DEFAULT_MEMORY_COST, ' ', PASSWORD_ARGON2_DEFAULT_TIME_COST, ' ',
    PASSWORD_ARGON2_DEFAULT_THREADS, "\n";
?>
--EXPECT--
bool(true)
bool(false)
bool(true)
bool(false)
bool(true)
bool(false)
bool(true)
bool(false)
bool(true)
bool(true)
bool(true)
bool(false)
array(3) {
  ["algo"]=>
  string(7) "argon2i"
  ["algoName"]=>
  string(7) "argon2i"
  ["options"]=>
  array(3) {
    ["memory_cost"]=>
    int(64)
    ["time_cost"]=>
    int(3)
    ["threads"]=>
    int(2)
  }
}
array(3) {
  ["algo"]=>
  string(8) "argon2id"
  ["algoName"]=>
  string(8) "argon2id"
  ["options"]=>
  array(3) {
    ["memory_cost"]=>
    int(65536)
    ["time_cost"]=>
    int(4)
    ["threads"]=>
    int(1)
  }
}
bool(false)
bool(true)
bool(true)
bool(true)
bool(false)
array(3) {
  [0]=>
  string(2) "2y"
  [1]=>
  string(7) "argon2i"
  [2]=>
  string(8) "argon2id"
}
argon2i argon2id 65536 4 1
--CLEAN--
<?php
